const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('game.js','utf8');
function method(n){const at=source.indexOf('  '+n+'('),tail=source.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);assert(at>=0&&next,n);return source.slice(at,at+1+next.index);}
const start=source.indexOf('const ASSET_SHEETS ='),end=source.indexOf('\n};',start)+3;
const defs=vm.runInNewContext(source.slice(start,end)+'\nASSET_SHEETS');
const regStart=source.indexOf('function registerEnemyActionAnimations('),regEnd=source.indexOf('const ASSET_SHEETS =',regStart);
const register=vm.runInNewContext(source.slice(regStart,regEnd)+'\nregisterEnemyActionAnimations',{ASSET_SHEETS:defs});
const clips=new Map(),textures=new Set(['e_ant_worker_animated','e_ant_scout_animated','e_ant_spitter_animated','e_ant_soldier_animated','e_ant_drone_animated','e_acid_animated']);
const anims={exists:k=>clips.has(k),generateFrameNumbers:(key,{start,end})=>Array.from({length:end-start+1},(_,i)=>({key,frame:start+i})),create(c){clips.set(c.key,c);}};
for(const key of textures){const d=defs[key];assert.equal(d.frame,96);assert.equal(d.anim.frames,6);assert.equal(d.facingLeft,!['e_ant_soldier_animated','e_acid_animated'].includes(key));anims.create({key:key+'_walk'});}
register({anims,textures:{exists:k=>textures.has(k)}});
const Scene=vm.runInNewContext('class Scene{'+['antArtKey','antSpitWindup','warnAntBomber','stopEnemyPresentation','resetEnemyPresentation','enemyAction','tickEnemyPresentation','spawnEnemy'].map(method).join('\n')+'\n}Scene',{Math,Phaser:{Math:{FloatBetween:a=>a}},stageCurveValue:()=>1,BALANCE:{}});
function mob(x,y,key){return {active:true,x,y,texture:{key},body:{velocity:{x:0,y:0}},anims:{isPlaying:false,isPaused:false,stop(){this.isPlaying=false;this.isPaused=false;},pause(){this.isPaused=true;},resume(){this.isPaused=false;}},setTexture(k,f){this.texture={key:k};this.frame=f;return this;},setCircle(...c){this.circle=c;return this;},setScale(x,y=x){this.scaleX=x;this.scaleY=y;return this;},setVelocity(x,y){this.body.velocity={x,y};return this;},setFlipX(){return this;},setTint(){return this;},clearTint(){return this;},play(k){this.clip=k;this.anims.isPlaying=true;return this;}};}
const s=new Scene();Object.assign(s,{stageIndex:0,waveIndex:0,W:300,H:500,viewZoom:1,player:{x:0,y:0},textures:{exists:k=>textures.has(k)},anims,enemies:{countActive:()=>0,getFirstDead:()=>null,create:mob},getPowerGuide:()=>({enemyHp:1,enemyDmg:1}),killPowerMul:()=>1,diffMul:()=>({hp:1,dmg:1}),newbieEase:()=>1,clearObjectiveTargetFx(){},camWorld:o=>o,vfxSpawnPoof(){}});
for(const [type,key,hp,dmg,scale,circle] of [['basic','worker',19,10,.74,[20,28,28]],['fast','scout',10,9,.68,[20,28,28]],['dasher','scout',16,14,.68,[20,28,28]],['shooter','spitter',19,9,.74,[20,28,28]],['bomber','drone',24,12,.74,[20,28,28]],['tank','soldier',80,18,.86,[25,23,23]],['siege','soldier',260,24,.86,[25,23,23]],['acid','acid',26,11,1,[22,26,26]]]){const e=s.spawnEnemy(type,0,100),expected=key==='acid'?'e_acid_animated':'e_ant_'+key+'_animated';assert.equal(e._enemyArtKey,expected);assert.equal(e.hp,hp);assert.equal(e.dmg,dmg);assert.equal(e.baseScale,scale);assert.deepEqual(e.circle,circle);assert.equal(e.clip,expected+'_idle');e.setVelocity(e.spd,0);s.tickEnemyPresentation(e,.016);assert.equal(e.clip,expected+'_walk');}
assert.equal(s.antArtKey('elite'),'e_ant_drone_animated');
{const e=s.spawnEnemy('shooter',0,100);e.shootCd=.1;s.antSpitWindup(e);assert.equal(e.clip,'e_ant_spitter_animated_windup');assert.equal(e.shootCd,.1,'Presentation cannot change shot timer');s.enemyAction(e,'attack',430);assert.equal(e.clip,'e_ant_spitter_animated_attack');assert.deepEqual(Array.from(clips.get(e.clip).frames,f=>f.frame),[10,11]);}
{const e=s.spawnEnemy('bomber',0,100);e.hp=e.maxhp*.3;s.warnAntBomber(e);assert.equal(e.clip,'e_ant_drone_animated_windup');const a=e._enemyAction;s.warnAntBomber(e);assert.equal(e._enemyAction,a,'One warning per life');s.resetEnemyPresentation(e);assert.equal(e._antBombWarn,false);}
{textures.delete('e_ant_worker_animated');textures.add('e_ant_worker_readable');assert.equal(s.antArtKey('basic'),'e_ant_worker_readable');textures.delete('e_ant_worker_readable');assert.equal(s.antArtKey('basic'),'e_ant_worker');}
for(const key of ['e_ant_worker_animated','e_ant_scout_animated','e_ant_spitter_animated','e_ant_soldier_animated','e_ant_drone_animated','e_acid_animated']){assert.equal(clips.get(key+'_hurt').frames.length,2);assert.deepEqual(Array.from(clips.get(key+'_death').frames,f=>f.frame),[14,15]);}
console.log('Ant art: all eight spawn roles, six clips, unchanged HP/damage/colliders, spit windup, bomber warning/reuse and fallback passed');
const facingLine=source.split('\n').find(l=>l.includes('const sheet=ASSET_SHEETS[e._enemyArtKey'));
assert(facingLine);
for(const [key,authoredLeft] of [['e_ant_worker_animated',true],['e_ant_scout_animated',true],['e_ant_spitter_animated',true],['e_ant_soldier_animated',false],['e_ant_drone_animated',true],['e_acid_animated',false]])for(const dx of [-20,20]){const e={_enemyArtKey:key,texture:{key},setFlipX(v){this.flip=v;}};vm.runInNewContext(facingLine,{e,dx,ASSET_SHEETS:defs});assert.equal(e.flip,authoredLeft?dx>0:dx<0,'Authored facing must track target');}
for(const id of ['worker','scout','spitter','soldier','drone','acid']){const b=fs.readFileSync('assets/incoming/ch1_ant_animations/'+id+'_sheet.png');assert.equal(b.readUInt32BE(16),1024);assert.equal(b.readUInt32BE(20),1024);assert.equal(b[25],6,'RGBA source sheets');assert(fs.existsSync('assets/art/ch1_ants/'+id+'_sheet.webp'));}
console.log('Ant art: both authored facing directions and six RGBA source/runtime sheets passed');
