const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('game.js','utf8'),capture=process.argv.includes('--capture');
function method(n){const at=source.indexOf('  '+n+'(');assert(at>=0,n);const tail=source.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);return source.slice(at,at+1+next.index);}
function constant(n){const a=source.indexOf('const '+n+' ='),b=source.indexOf('\n};',a)+3;return vm.runInNewContext(source.slice(a,b)+';'+n);}
const defs=constant('ASSET_SHEETS'),balance=constant('BALANCE'),clips=new Map(),textures=new Set();
const groups=[{stage:8,prefix:'c24_',ids:['budling','sunscarab','leafblade','frostbell','stormfruit','equinox','season_wisp'],dir:'ch2_s4_animations',atlas:'ch2_seasons_enemy_atlas'}, {stage:9,prefix:'c25_',ids:['rootling','thorn_charger','bramble_assassin','sap_oracle','seed_bomb','bark_guard','root_choir'],dir:'ch2_s5_animations',atlas:'ch2_root_enemy_atlas'}];
for(const g of groups)for(const id of g.ids){const key=g.prefix+id+'_animated';if(!capture)textures.add(key);}
const anims={exists:k=>clips.has(k),generateFrameNumbers:(key,{start,end})=>Array.from({length:end-start+1},(_,i)=>({key,frame:start+i})),create(c){clips.set(c.key,c);}};
if(!capture){for(const k of textures)anims.create({key:k+'_walk'});const a=source.indexOf('function registerEnemyActionAnimations('),b=source.indexOf('const ASSET_SHEETS =',a);vm.runInNewContext(source.slice(a,b)+';registerEnemyActionAnimations',{ASSET_SHEETS:defs})({anims,textures:{exists:k=>textures.has(k)}});}
const names=['nectarArtKey','myceliumArtKey','canopyArtKey','antArtKey','drainArtKey','fireArtKey','iceArtKey','stage5ArtKey','chapter3ArtKey','antSpitWindup','warnAntBomber','stopEnemyPresentation','resetEnemyPresentation','enemyAction','tickEnemyPresentation','spawnEnemy','spawnElite','playEnemyDeath','applySpecialEnemyArt'];if(!capture)names.push('seasonArtKey','rootArtKey');
const Scene=vm.runInNewContext('class Scene{'+names.map(method).join('\n')+'\n}Scene',{Math,Phaser:{Math:{FloatBetween:a=>a,Between:a=>a}},stageCurveValue:(i,a,t=1.18)=>i<a.length?a[i]:a.at(-1)*t**(i-a.length+1),ASSET_SHEETS:defs,BALANCE:balance});
function mob(x,y,key){return {active:true,x,y,width:256,texture:{key},body:{velocity:{x:0,y:0}},anims:{isPlaying:false,isPaused:false,stop(){this.isPlaying=false;this.isPaused=false;},pause(){this.isPaused=true;},resume(){this.isPaused=false;}},setTexture(k,f){this.texture={key:k};this.frame=f;return this;},setActive(a){this.active=a;return this;},setVisible(){return this;},setPosition(x,y){this.x=x;this.y=y;return this;},setCircle(...c){this.circle=c;this.body.isCircle=true;this.body.radius=c[0];this.body.offset={x:c[1],y:c[2]};return this;},setScale(x,y=x){this.scaleX=x;this.scaleY=y;return this;},setVelocity(x,y){this.body.velocity={x,y};return this;},setFlipX(){return this;},setTint(){return this;},clearTint(){return this;},play(k){this.clip=k;this.anims.isPlaying=true;return this;}};}
function aura(){return {active:true,setTint(v){this.tint=v;return this;},setDisplaySize(w,h){this.size=[w,h];return this;},setAlpha(v){this.alpha=v;return this;},setDepth(v){this.depth=v;return this;},destroy(){this.active=false;}};}
const s=new Scene();let recycled=null;Object.assign(s,{stageIndex:8,waveIndex:0,W:300,H:500,viewZoom:1,player:{x:0,y:0},textures:{exists:k=>textures.has(k)},anims,enemies:{countActive:()=>0,getFirstDead:()=>recycled,create:mob},getPowerGuide:()=>({enemyHp:1,enemyDmg:1}),killPowerMul:()=>1,diffMul:()=>({hp:1,dmg:1}),newbieEase:()=>1,clearObjectiveTargetFx(){},camWorld:o=>o,vfxSpawnPoof(){},add:{image:()=>aura()}});
function combat(e){return {hp:e.hp,dmg:e.dmg,spd:e.spd,xp:e.xp,baseScale:e.baseScale,circle:e.circle,shooter:e.shooter,bomber:e.bomber,dasher:e.dasher,siege:e.siege,shootCd:e.shootCd,roleName:e.roleName,seasonRole:e.seasonRole,rootRole:e.rootRole,aura:e._aura?{size:e._aura.size,tint:e._aura.tint,alpha:e._aura.alpha}:null};}
const roles=['basic','fast','dasher','shooter','bomber','tank','siege'],fixture='tests/fixtures/batch9-combat.json',saved=capture?{}:JSON.parse(fs.readFileSync(fixture,'utf8'));
for(const g of groups){s.stageIndex=g.stage;
 for(let i=0;i<roles.length;i++){
  const type=roles[i],key=g.prefix+g.ids[i]+'_animated',label=g.stage+':'+type,e=s.spawnEnemy(type,0,100);
  if(capture){saved[label]={combat:combat(e),fallbackFrame:e._enemyRestFrame};continue;}
  assert.equal(JSON.stringify(combat(e)),JSON.stringify(saved[label].combat));assert.equal(e.texture.key,key);assert.equal(e._enemyRestFrame,0);assert.equal(e.clip,key+'_idle');
  e.setVelocity(80,0);s.tickEnemyPresentation(e,.016);assert.equal(e.clip,key+'_walk');s.enemyAction(e,'attack',340);assert.equal(e.clip,key+'_attack');e.frozen=1;s.tickEnemyPresentation(e,2);assert(e.anims.isPaused);assert.equal(e._enemyActionT,.34);e.frozen=0;s.tickEnemyPresentation(e,.35);assert.equal(e.clip,key+'_walk');
  if(type==='shooter'||type==='siege'){e.shootCd=.1;s.antSpitWindup(e);assert.equal(e.clip,key+'_windup');assert.equal(e.shootCd,.1);}
  if(type==='dasher'){s.enemyAction(e,'windup',500);assert.equal(e.clip,key+'_windup');s.enemyAction(e,'dash',320);assert.equal(e.clip,key+'_dash');}
  if(type==='bomber'){e.hp=e.maxhp*.3;s.warnAntBomber(e);assert.equal(e.clip,key+'_windup');const warning=e._enemyAction;s.warnAntBomber(e);assert.equal(e._enemyAction,warning);recycled=e;const reuse=s.spawnEnemy('basic',0,100);assert.equal(reuse,e);assert.equal(reuse._antBombWarn,false);assert(!reuse.bomber);assert.equal(reuse._enemyAction,null);assert.equal(reuse.clip,g.prefix+g.ids[0]+'_animated_idle');recycled=null;}
  textures.delete(key);const old=s.spawnEnemy(type,0,100);assert.equal(old.texture.key,g.atlas);assert.equal(old._enemyRestFrame,saved[label].fallbackFrame);assert.equal(JSON.stringify(combat(old)),JSON.stringify(saved[label].combat));textures.add(key);
 }
 if(g.stage===8){const e=s.spawnElite();if(capture)saved['8:elite']={combat:combat(e),fallbackFrame:e._enemyRestFrame};else {assert.equal(e.texture.key,'c24_equinox_animated');assert.equal(JSON.stringify(combat(e)),JSON.stringify(saved['8:elite'].combat));assert.deepEqual(e.circle,[48,80,80]);assert.equal(e.baseScale,.42);textures.delete('c24_equinox_animated');const old=s.spawnElite();assert.equal(old.texture.key,g.atlas);assert.equal(old._enemyRestFrame,5);textures.add('c24_equinox_animated');}}
}
if(capture){fs.mkdirSync('tests/fixtures',{recursive:true});fs.writeFileSync(fixture,JSON.stringify(saved,null,2)+'\n');console.log('Captured original Batch 9 combat and fallback frames');process.exit(0);}
for(const g of groups){s.stageIndex=g.stage;const e=s.spawnEnemy('basic',0,100);let finished,created=0;const ghost={setScale(){return this;},setFlipX(){return this;},setDepth(){return this;},once(event,fn){assert.equal(event,'animationcomplete');finished=fn;},play(key){assert.equal(key,e._enemyArtKey+'_death');},destroy(){this.destroyed=true;}};s.fxOk=()=>true;s.trackArtVfx=o=>o;s.add.sprite=()=>{created++;return ghost;};s.playEnemyDeath(e);assert.equal(created,1);finished();assert(ghost.destroyed);}
const a=source.indexOf('const STAGE_SHEETS='),b=source.indexOf('\n];',a)+3,stages=vm.runInNewContext(source.slice(a,b)+';STAGE_SHEETS');
for(const g of groups){const pack=JSON.parse(fs.readFileSync('assets/incoming/'+g.dir+'/PACKING.json','utf8'));for(const id of g.ids){const stem=g.prefix+id,key=stem+'_animated';assert(stages[g.stage].includes(key));assert(!stages[g.stage===8?9:8].includes(key));const png=fs.readFileSync('assets/incoming/'+g.dir+'/'+stem+'_sheet.png');assert.equal(png.readUInt32BE(16),1024);assert.equal(png.readUInt32BE(20),1024);assert.equal(png[25],6);const webp=fs.readFileSync(defs[key].url);assert.equal(webp.toString('ascii',12,16),'VP8L');const dimensions=webp.readUInt32LE(21);assert(dimensions&(1<<28));assert.equal((dimensions&0x3fff)+1,1024);assert.equal(((dimensions>>>14)&0x3fff)+1,1024);assert.equal(pack[stem].bounds.length,16);for(const [x,y,w,h] of pack[stem].bounds){assert(x>=10&&y>=10);assert.equal(y+h,236);assert(x+w<=246);}assert.deepEqual(Array.from(clips.get(key+'_death').frames,f=>f.frame),[14,15]);}}
assert(source.includes("this.stageIndex===9?.78:this.stageIndex===8?.76"));assert(source.includes("e.seasonRole==='seasonWisp'"));assert(source.includes("e.rootRole==='rootChoir'"));
console.log('Batch 9: 14 actual roles plus Equinox Elite preserve captured combat/colliders/auras, per-species fallback, action/freeze/pool lifecycle and stage/alpha-sheet contracts passed');
