const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),s=fs.readFileSync('game.js','utf8'),before=fs.readFileSync('tests/fixtures/cocoa-rework-baseline.json','utf8');
function block(a,b){const at=s.indexOf(a),end=s.indexOf(b,at);assert(at>=0&&end>at,a);return s.slice(at,end);}
function method(n){const at=s.indexOf('  '+n+'(',s.indexOf('class Game extends')),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(s.slice(at+1));assert(at>=0&&next,n);return s.slice(at,at+1+next.index);}
const ctx={SKILL_AWAKEN_LV:6,Phaser:{Math:{Between:()=>0}},TAU:Math.PI*2,CF:{},CHARACTERS:{cocoa:{unique:'flickerStrike'},mint:{unique:'mintSanctuary'}},Sfx:{comboPunch(){},beatFx(){},dash(){},clear(){}}};vm.createContext(ctx);
vm.runInContext(block('const BASIC_ATTACKS = {','// 🛤 Build Path')+block('const BASIC_PATHS={','// 🍯 Flavor Infusion')+block('const BUILD_PATH_STYLES=','// Mint M1:')+block('// Chocolate keeps saved','/* ---- TALENTS:'),ctx);
const api=vm.runInContext('({BASIC_ATTACKS,BASIC_PATHS,COCOA_UNIQUES,COCOA_EVOLUTIONS,UNIQUE_TIERS,CHARACTER_UNIQUES,uniqueAt,pathMods,cocoaAttackInfo})',ctx);
const names=['finishCocoaFlicker','cocoaWarpTo','cocoaComboHold','clearCocoaCombat','cocoaLater','tickCocoaCombat','cocoaHit','castCocoaRush','cocoaOnDash','cocoaPriorityTarget','castCocoaUnique','cocoaStartTrail','startCocoaFlicker','cocoaFlickerTarget','cocoaFlickerRetreat','tickCocoaFlicker','drawCocoaComboDots','cocoaLandingFx','cocoaDashLeap','cocoaGlideTo','tickCocoaGlide','cocoaTrailHit','tickCocoaCombo','cocoaBossLeech','cocoaBeatCharge','cocoaDashMax','cocoaDashRecharge','cocoaDashCdMul','cocoaDashBuffPct','cocoaDashBuffMul','tickCocoaDash','cancelBeat','doDash','uniqueInfo','uniquePower','uniqueCooldown','useCharacterSkill','checkUniqueAutoUpgrade','cdOf','_cdBase'];
const Scene=vm.runInContext('class Scene{'+names.map(method).join('\n')+'\n} Scene',ctx);
function foe(x=65,y=0,extra={}){return {x,y,active:true,hp:100000,maxhp:100000,velocity:{x:0,y:0},setVelocity(x,y){this.velocity={x,y};},...extra};}
function scene(path,foes=[foe()]){const q=new Scene(),p={x:0,y:0,active:true,hp:80,maxhp:100,dmgMul:1,cdMul:1,iframe:0,setFlipX(){},setVelocity(x,y){this.velocity={x,y};},setTint(){},clearTint(){}};let rec=[];Object.assign(q,{character:'cocoa',state:'play',elapsed:0,uniqueLevel:1,uniqueCd:0,level:1,player:p,signatureWeaponInfo:()=>({skill:'meteor'}),basicAttackInfo:()=>({skill:'meteor'}),skillCd:{meteor:0},dashTime:0,_dpCh:2,_dpT:0,joy:{active:false},moveDir:{x:1,y:0,lengthSq:()=>1,angle:()=>0,clone(){return {x:1,y:0,normalize(){return this;}}}},basicAttack:{character:'cocoa',path,lv:{},ranks:{},endless:{},_pm:{dmg:1,cd:1}},enemies:{children:{iterate:fn=>foes.forEach(fn)}},dist:(x,y,a,b)=>Math.hypot(x-a,y-b),nearestEnemy:r=>foes.filter(e=>e.active&&Math.hypot(e.x-p.x,e.y-p.y)<=r).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]||null,damage:(e,power)=>rec.push({e,power,x:p.x,y:p.y}),hitCratesInRadius(){},cocoaVisual(){},cocoaMark:()=>({active:true,destroy(){this.active=false}}),cocoaUnmark:g=>g&&g.destroy(),screenShake(){},showBanner:(a,b)=>{q.banner=[a,b]},poseAttack(){},flashBtn(){},fireRecipes(){},charPassiveOnDash(){},ancientEchoDash(){},cocoaDashBuff(){q._dashBuffT=2.5},time:{delayedCall(){}} ,camWorld:g=>g,add:{circle:()=>({setDepth(){return this}})},tweens:{killTweensOf(){},add(){}},refreshUniqueSkillUI(){},playGrowthWorld(){}});q.rec=rec;q.foes=foes;q.basicAttack._pm=api.pathMods(q.basicAttack);return q;}
function advance(q,seconds,step=.01){for(let t=0;t<seconds-1e-9;t+=step){const dt=Math.min(step,seconds-t);if(q.state==='play')q.elapsed+=dt;q.tickCocoaCombat(dt);if(q.state==='play'){q.tickCocoaCombo(dt);q.tickCocoaDash(dt);}}}
function punch(q){q.castCocoaRush(1,false,q.basicAttack._pm.dmg,false,q.basicAttack);advance(q,.4);}
// Basic progress depends on hits, never swinging at empty space or an immune phase.
for(const path of ['brawler','titan','dashboxer']){const q=scene(path,[foe(500)]);punch(q);assert.equal(q._cc.step,0);assert.equal(q._cc.n,0);q.foes[0].x=65;for(let i=0;i<5;i++)punch(q);assert.equal(q._cc.step,0);assert.equal(q._cc.n,5);assert(q.rec.length>=5);q.foes[0].x=500;advance(q,q.cocoaComboHold()+.1);assert.equal(q._cc.step,0);assert.equal(q._cc.n,0);}
{const q=scene('titan',[foe(65,0,{isBoss:true,_phaseGateLocked:true})]);punch(q);assert.equal(q._cc.n,0);assert.equal(q.rec.length,0);q.foes[0]._phaseGateLocked=false;punch(q);assert.equal(q._cc.n,1);}
{const dead=foe(60),next=foe(-65),q=scene('brawler',[dead,next]);q.castCocoaRush(1,false,1,false,q.basicAttack);dead.active=false;advance(q,.1);assert.equal(q.rec[0].e,next);}
// Titan wind-up remains fixed even at maximum haste; its marked impact stays in world space.
{const q=scene('titan');q.basicAttack.ranks.rate=7.75;q.castCocoaRush(1,false,1,false,q.basicAttack);advance(q,.2);assert.equal(q.rec.length,0);advance(q,.05);assert.equal(q.rec.length,1);}
{const q=scene('titan');q.basicAttack.ranks.rate=7.75;q.player.cdMul=.3;q.basicAttack._pm.cd=.2;assert(q.cdOf('meteor',5)*q.player.cdMul>=.5);}
// Finisher budgets include old card/Talent wave investment without unbounded waves.
{const q=scene('brawler');q._cc={step:4,n:4,t:0,gen:0};q.basicAttack._pm.wave=20;q.castCocoaRush(1,false,1,true,q.basicAttack);advance(q,1);assert.equal(q.rec.length,6);assert(q.rec[1].power<q.rec[0].power);}
// Each Evolution adds its own mechanic and Earthbreaker does not stack two echoes.
for(const path of ['titan','dashboxer']){const q=scene(path);q._cc={step:path==='titan'?4:0,n:4,t:0,gen:0};q.basicAttack.evolved=true;q.basicAttack.mutation=path==='titan'?'breaker':null;if(path==='dashboxer'){q._cocoaNextPunch=true;q._dashBuffT=2.5;}q.castCocoaRush(1,false,1,true,q.basicAttack);advance(q,1);assert.equal(q.rec.length,2);assert(!q._cocoaNextPunch||path!=='dashboxer');}
{const q=scene('brawler');q._cc={step:4,n:4,t:0,gen:0};q.basicAttack.mutation='rush';q.castCocoaRush(1,false,1,false,q.basicAttack);advance(q,1);assert.equal(q.rec.length,4);}
// Unique skills are one tap, independent of aim/swipe, and never move or lock the player.
for(const path of [null,'brawler','titan','dashboxer'])for(let lv=1;lv<=4;lv++){const q=scene(path);q.uniqueLevel=lv;const xy=[q.player.x,q.player.y];q.useCharacterSkill();assert(q.uniqueCd>0);assert.equal(q._coachUnique,1);assert(!q._beat&&!q._ubHold);assert.deepEqual([q.player.x,q.player.y],xy);const jobs=q._cocoaJobs?.length||0;q.uniqueCd=0;q.useCharacterSkill();assert.equal(q._cocoaJobs?.length||0,jobs,'cannot overlap on level-up reset');advance(q,2);if(path==='brawler')assert.equal(q.rec.length,7+(lv-1)*2);if(path==='titan')assert.equal(q.rec.length,2);if(!path)assert.equal(q.rec.length,1);if(path==='dashboxer')assert.equal(q.rec.length,0);}
// Cyclone follows actual movement between pulses.
{const q=scene('brawler',[foe(0),foe(400)]);q.useCharacterSkill();advance(q,.02);assert(q.rec.some(r=>r.e===q.foes[0]));q.player.x=400;advance(q,1.3);assert(q.rec.some(r=>r.e===q.foes[1]));assert.equal(q.player.x,400);}
// Titan target priority, fixed location, central damage and no-target fallback.
{const normal=foe(40,0,{maxhp:9999999}),elite=foe(90,0,{isElite:true}),mini=foe(150,0,{isMini:true}),boss=foe(230,0,{isBoss:true}),q=scene('titan',[normal,elite,mini,boss]);assert.equal(q.cocoaPriorityTarget(480),boss);boss.active=false;assert.equal(q.cocoaPriorityTarget(480),mini);mini.active=false;assert.equal(q.cocoaPriorityTarget(480),elite);elite.active=false;assert.equal(q.cocoaPriorityTarget(480),normal);}
{const target=foe(200,0,{isBoss:true}),center=foe(200),outer=foe(285),q=scene('titan',[target,center,outer]);q.useCharacterSkill();target.active=false;q.player.x=600;advance(q,.4);assert.equal(q.rec.length,2);assert(q.rec.find(r=>r.e===center).power>q.rec.find(r=>r.e===outer).power*3);advance(q,.4);assert.equal(q.rec.length,4);assert.equal(q.player.x,600);}
{const q=scene('titan',[]);q.useCharacterSkill();advance(q,1);assert.equal(q.rec.length,0);assert.equal(q._cocoaJobs.length,0);}
// Dash retains progress only on Dash Boxer and empowers exactly one landed primary punch.
for(const path of ['brawler','titan','dashboxer']){const q=scene(path);q._cc={step:3,n:3,t:1,gen:0,busy:true};q.doDash();assert.equal(q._cc.step,path==='dashboxer'?3:0);assert.equal(q._cc.busy,false);assert.equal(q._dpCh,1);assert.deepEqual(q.player.velocity,path==='dashboxer'?{x:0,y:0}:{x:560,y:0});assert.equal(q.player.x,0);}
// Temporary charges are consumed first, expire without changing regular capacity or stored rank data.
for(let lv=1;lv<=4;lv++){const q=scene('dashboxer',[foe(55),foe(90),foe(50,90)]);q.uniqueLevel=lv;q.basicAttack.lv.dashp=3;q.basicAttack.lv.p_blitz=2;q.basicAttack._pm=api.pathMods(q.basicAttack);q._dpCh=q.cocoaDashMax();const normal=q._dpCh,ranks=JSON.stringify(q.basicAttack.lv);q.useCharacterSkill();const temp=q._cocoaPhantom.charges;q.doDash();assert.equal(q._dpCh,normal);assert.equal(q._cocoaPhantom.charges,temp-1);q.player.x=60;advance(q,.01);q.player.x=100;advance(q,.01);q.player.x=60;advance(q,.01);assert.equal(q.rec.filter(r=>r.e===q.foes[0]).length,1);assert.equal(q.rec.filter(r=>r.e===q.foes[1]).length,1);assert(!q.rec.some(r=>r.e===q.foes[2]));q.dashTime=0;advance(q,8);assert(!q._cocoaPhantom&&!q._cocoaTrail);assert.equal(q._dpCh,normal);assert.equal(JSON.stringify(q.basicAttack.lv),ranks);}
// Empty charges cannot Dash; regular Dash still works after temporary mode expires.
{const q=scene('dashboxer');q._dpCh=0;q.doDash();assert(!q.player.velocity);q.useCharacterSkill();q.doDash();assert(q.player.velocity);assert.equal(q._dpCh,0);q.dashTime=0;q.clearCocoaCombat();q.player.velocity=null;q.doDash();assert(!q.player.velocity);}
// Cooldown refunds respect the minimum reuse interval and Drum Heart strengthens refunds.
{const q=scene('brawler');q.useCharacterSkill();q.cocoaBeatCharge(999);assert.equal(q.uniqueCd,q._cocoaMinGap);q.elapsed=20;q.uniqueCd=10;q.basicAttack.lv.drum=3;q.cocoaBeatCharge(1);assert.equal(q.uniqueCd,8.55);}
// Paused/level-up time cannot consume attacks. Cancellation, changed basic/player/path cannot damage a new run.
for(const state of ['paused','levelup']){const q=scene('titan');q.useCharacterSkill();q.state=state;advance(q,5);assert.equal(q.rec.length,0);q.state='play';advance(q,.4);assert.equal(q.rec.length,1);}
for(const mode of ['cancel','path','basic','player']){const q=scene('titan');q.useCharacterSkill();if(mode==='cancel')q.cancelBeat();if(mode==='path')q.basicAttack.path='brawler';if(mode==='basic')q.basicAttack={...q.basicAttack};if(mode==='player')q.player={...q.player};advance(q,2);assert.equal(q.rec.length,0,mode);}
{const q=scene('brawler');for(let i=0;i<60;i++)q.cocoaLater(0,()=>q.rec.push(1));assert.equal(q._cocoaJobs.length,32);q.tickCocoaCombat(.02);assert.equal(q.rec.length,4);}
{const q=scene('brawler');q.useCharacterSkill();const damage=q.damage;q.damage=(e,p)=>{damage(e,p);q.state='levelup';};q.tickCocoaCombat(2);assert.equal(q.rec.length,1);assert(q._cocoaJobs.length>0);}
// Path Evolution/UI helpers retain core IDs and old Recipe ranks; other hero definitions stay unchanged.
const baseline=JSON.parse(before);for(const [hero,data] of Object.entries(baseline.heroes)){if(hero==='cocoa')continue;assert.equal(JSON.stringify(api.BASIC_ATTACKS[hero]),data.basic);assert.equal(JSON.stringify(api.BASIC_PATHS[hero]),data.paths);}
for(const path of ['brawler','titan','dashboxer']){const q=scene(path);q.basicAttack.lv={dashp:3,drum:2,combo:3};const old=JSON.stringify(q.basicAttack);const d=api.cocoaAttackInfo(api.BASIC_ATTACKS.cocoa,q.basicAttack);assert.equal(d.evolution,api.COCOA_EVOLUTIONS[path].name);assert.deepEqual(Array.from(d.upgrades,u=>u.id),baseline.cocoaUpgradeIds);assert.equal(JSON.stringify(q.basicAttack),old);q.level=11;q.checkUniqueAutoUpgrade();assert.equal(q.uniqueLevel,4);assert(q.banner[1].includes(api.COCOA_UNIQUES[path].tiers[4]));}
assert(!s.includes('startBeatRush('));assert(!s.includes('beatHoldNodes('));assert(!s.includes('this._ubHold'));assert(!s.includes('castFlickerStrike('));
console.log('Chocolate C1–C5: landed combos, three one-tap Uniques, moving Cyclone, locked Titan targeting/echo, Dash retention/temporary charges/dedup, Evolutions/mutations, cooldown floor, pause/cancellation/budgets, saved IDs and other-hero isolation passed');
