const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),s=fs.readFileSync('game.js','utf8'),before=fs.readFileSync('tests/fixtures/cocoa-rework-baseline.json','utf8');
function block(a,b){const at=s.indexOf(a),end=s.indexOf(b,at);assert(at>=0&&end>at,a);return s.slice(at,end);}
function method(n){const at=s.indexOf('  '+n+'(',s.indexOf('class Game extends')),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(s.slice(at+1));assert(at>=0&&next,n);return s.slice(at,at+1+next.index);}
const ctx={WORLD:4000,SKILL_AWAKEN_LV:6,Phaser:{Math:{Between:()=>0}},TAU:Math.PI*2,CF:{hurt:5},CHARACTERS:{cocoa:{unique:'flickerStrike'},mint:{unique:'mintSanctuary'}},Sfx:{uiAction(k,fn){fn();},comboPunch(){},beatFx(){},dash(){},clear(){}}};vm.createContext(ctx);
vm.runInContext(block('const BASIC_ATTACKS = {','// 🛤 Build Path')+block('const BASIC_PATHS={','// 🍯 Flavor Infusion')+block('const BUILD_PATH_STYLES=','// Mint M1:')+block('// Chocolate keeps saved','/* ---- TALENTS:'),ctx);
const api=vm.runInContext('({BASIC_ATTACKS,BASIC_PATHS,COCOA_UNIQUES,COCOA_EVOLUTIONS,UNIQUE_TIERS,CHARACTER_UNIQUES,uniqueAt,pathMods,cocoaAttackInfo})',ctx);
const names=['poseFlash','toggleCocoaFlicker','refreshFlickerUI','cocoaFlickerTarget','cocoaFlickerRetreat','startCocoaFlicker','tickCocoaFlicker','finishCocoaFlicker','cocoaWarpTo','cocoaGlideTo','tickCocoaGlide','cocoaDashLeap','drawCocoaComboDots','cocoaLandingFx','cocoaComboHold','clearCocoaCombat','cocoaLater','tickCocoaCombat','cocoaHit','castCocoaRush','titanRageSpend','cocoaFireFist','cocoaPool','tickCocoaPools','cocoaLeapMutation','titanRageImpact','cocoaOnDash','cocoaPriorityTarget','castCocoaUnique','cocoaStartTrail','cocoaTrailHit','tickCocoaCombo','cocoaBossLeech','cocoaBeatCharge','cocoaDashMax','cocoaDashRecharge','cocoaDashCdMul','cocoaDashBuffPct','cocoaDashBuffMul','tickCocoaDash','cancelBeat','doDash','uniqueInfo','uniquePower','uniqueCooldown','useCharacterSkill','checkUniqueAutoUpgrade','cdOf','_cdBase'];
const Scene=vm.runInContext('class Scene{'+names.map(method).join('\n')+'\n} Scene',ctx);
function foe(x=65,y=0,extra={}){return {x,y,active:true,hp:100000,maxhp:100000,velocity:{x:0,y:0},setVelocity(x,y){this.velocity={x,y};},...extra};}
function scene(path,foes=[foe()]){const q=new Scene(),p={x:0,y:0,active:true,hp:80,maxhp:100,dmgMul:1,cdMul:1,iframe:0,setFlipX(){},setVelocity(x,y){this.velocity={x,y};},setTint(){},clearTint(){}};let rec=[];Object.assign(q,{character:'cocoa',state:'play',elapsed:0,uniqueLevel:1,uniqueCd:0,level:1,player:p,signatureWeaponInfo:()=>({skill:'meteor'}),basicAttackInfo:()=>({skill:'meteor'}),skillCd:{meteor:0},dashTime:0,_dpCh:2,_dpT:0,joy:{active:false},moveDir:{x:1,y:0,lengthSq:()=>1,angle:()=>0,clone(){return {x:1,y:0,normalize(){return this;}}}},basicAttack:{character:'cocoa',path,lv:{},ranks:{},endless:{},_pm:{dmg:1,cd:1}},enemies:{children:{iterate:fn=>foes.forEach(fn)}},dist:(x,y,a,b)=>Math.hypot(x-a,y-b),nearestEnemy:r=>foes.filter(e=>e.active&&Math.hypot(e.x-p.x,e.y-p.y)<=r).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0]||null,getBullet:()=>{const b={setTexture(){return b;},setTint(){return b;},setScale(){return b;}};Object.defineProperty(b,'dmg',{set(v){const t=q.nearestEnemy(9999);if(t)rec.push({e:t,power:v,fire:true});}});return b;},damage:(e,power)=>rec.push({e,power,x:p.x,y:p.y}),hitCratesInRadius(){},cocoaVisual(){},cocoaMark:()=>({active:true,destroy(){this.active=false}}),cocoaUnmark:g=>g&&g.destroy(),screenShake(){},showBanner:(a,b)=>{q.banner=[a,b]},poseAttack(){},flashBtn(){},fireRecipes(){},charPassiveOnDash(){},ancientEchoDash(){},cocoaDashBuff(){q._dashBuffT=2.5},time:{delayedCall(){}} ,camWorld:g=>g,add:{circle:()=>({setDepth(){return this}})},tweens:{killTweensOf(){},add(){}},refreshUniqueSkillUI(){},playGrowthWorld(){}});q.rec=rec;q.foes=foes;q.basicAttack._pm=api.pathMods(q.basicAttack);return q;}
function advance(q,seconds,step=.01){for(let t=0;t<seconds-1e-9;t+=step){const dt=Math.min(step,seconds-t);if(q.state==='play')q.elapsed+=dt;q.tickCocoaCombat(dt);if(q.state==='play'){q.tickCocoaCombo(dt);q.tickCocoaDash(dt);}}}
function punch(q){q.castCocoaRush(1,false,q.basicAttack._pm.dmg,false,q.basicAttack);advance(q,.4);}

function mobile(path,foes=[foe(130,0,{isBoss:true})]){const q=scene(path,foes),p=q.player;const v={x:0,y:0};p.setPosition=(x,y)=>{p.x=x;p.y=y;return p;};p.setVelocity=(x,y)=>{v.x=x;v.y=y;p.velocity={x,y};};p.body={velocity:v,reset(x,y){p.x=x;p.y=y;v.x=0;v.y=0;}};q.joy={active:false,dx:0,dy:0};q.cameras={main:{startFollow(target){q.follow=target;}}};return q;}
function tick(q,t,step=.01){for(let n=0;n<t-1e-9;n+=step){const dt=Math.min(step,t-n);q.tickCocoaFlicker(dt);advance(q,dt,dt);}}
// OFF keeps the original close-range behavior; ON reaches a boss without living at its feet.
// Flicker is Brawler-only and automatic: no button, short 150px reach, two split punches, stays beside the target.
// v6.59.5 Brawler = Fire Fist: never flickers or moves; fires a projectile at a target in range, nothing when out of range.
{const q=mobile('brawler',[foe(300,0)]);q.castCocoaRush(1,false,1,false,q.basicAttack);assert(!q._cocoaFlicker,'fire fist never flickers');tick(q,.4);assert.equal(q.player.x,0);assert.equal(q.rec.length,1,'one fire fist');assert(q.rec[0].fire);}
{const q=mobile('brawler',[foe(900,0)]);q.castCocoaRush(1,false,1,false,q.basicAttack);tick(q,.4);assert.equal(q.rec.length,0,'nothing in range');}
for(const path of ['titan','dashboxer']){const q=mobile(path);q.castCocoaRush(1,false,1,false,q.basicAttack);assert(!q._cocoaFlicker,path+' never flickers');assert.equal(q.player.x,0);}
{const q=mobile('brawler');const btn={visible:true,setVisible(v){this.visible=v;return this;},setFillStyle(){return this;},setStrokeStyle(){return this;}};q.flickerBtn=btn;q.flickerTxt={setVisible(){return this;},setText(){return this;}};q.refreshFlickerUI();assert.equal(q.flickerBtn.visible,false,'no Flicker button');}
// The boss remains locked over a closer ordinary foe; joystick heading chooses ordinary targets; retreat never starts a chain.
// Mid-chain retreat, Dash and hurt cancel pending hits.
// Dash Boxer Dash leaps to an aimed monster and slams on landing; with nothing in range it is a normal Dash.
{const q=mobile('dashboxer');q.doDash();assert.equal(q.player.velocity.x,0);assert(q._cocoaGlide);tick(q,.4);assert(q.player.x>60,'leapt to target');assert(q.rec.length>=1,'landing slam');}
{const q=mobile('dashboxer',[foe(900,0)]);q.doDash();assert.equal(q.player.velocity.x,560);assert(!q._cocoaGlide);}
// World bounds, pause, reset/path/dead target, saturation and large ticks never strand a chain.
// Combo dots: five dots above Chocolate, drawn only while a combo is in progress.
console.log('Flicker: Brawler Fire Fist projectiles, Titan/Dash Boxer stand/leap, boss lock/aim, retreat/Dash/hurt cancellation, Dash Leap, bounds, pause/reset/stale targets and bounded jobs passed');


// Hurt cancels pending punches, and replacing a player cannot leave the camera following a stale anchor.

// Actual auto-cast loop waits for a chain instead of wasting a full cooldown on a blocked cast.
