const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync('game.js','utf8');
function method(n){const a=source.indexOf('  '+n+'(',source.indexOf('class Game extends')),m=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(source.slice(a+1));assert(a>=0&&m,n);return source.slice(a,a+1+m.index);}
let now=0;const ctx={TAU:Math.PI*2,RENDER_DPR:2,Save:{data:{settings:{}}},performance:{now:()=>now},Sfx:{beatFx(){},unlock(){},uiAction(k,fn){fn();}},Phaser:{Math:{Clamp:(n,a,b)=>Math.max(a,Math.min(b,n))}}};vm.createContext(ctx);
const C=vm.runInContext('class Controls{'+['updateUniqueHint','refreshFlickerUI','toggleCocoaFlicker','layoutControls','ctrlScale','drawUniqueRing','isSniperUnique','isBlastUnique','mintChargeKind','snipeCharge','snipeMods','setupInput','hudVisible','startSnipeCharge'].map(method).join('\n')+'} Controls',ctx);
function node(x=0,y=0,r=36){return {x,y,radius:r,width:62,height:46,visible:true,text:'',setText(t){this.text=t;return this},setAlpha(a){this.alpha=a;return this},setVisible(v){this.visible=v;return this},setPosition(x,y){this.x=x;this.y=y;return this},setScale(k){this.scale=k;return this},setRadius(r){this.radius=r;return this},setSize(w,h){this.width=w;this.height=h;return this},setFillStyle(){return this},setStrokeStyle(){return this}};}
function scene(character,path){const s=new C();Object.assign(s,{character,state:'play',basicAttack:{path,lv:{},ranks:{}},player:{},uniqueCd:0,W:390,H:844,uniqueBtn:node(),uniqueTxt:node(),uniqueHint:node(),flickerBtn:node(),flickerTxt:node(),dashBtn:node(),dashTxt:node(),joy:{active:false},uniqueInfo:()=>({color:0x123456}),uniqueCooldown:()=>10,dist:(x,y,a,b)=>Math.hypot(x-a,y-b),renderWaveObjectiveHUD(){}});s.arcs=[];s.uniqueRing={clear(){return this},lineStyle(){return this},strokeCircle(){return this},beginPath(){return this},arc(...a){s.arcs.push(a);return this},strokePath(){return this}};s.layoutControls();return s;}
// Four charged Uniques advertise HOLD; charge progress and RELEASE live on the button.
for(const [hero,path,ms] of [['momo','sniper',1100],['momo','shotgun',450],['mint','glacier',1000],['mint','pierce',400]]){const s=scene(hero,path);s.updateUniqueHint();assert.equal(s.uniqueHint.text,'HOLD');now=0;s._snipe={t0:0,blast:path==='shotgun',kind:s.mintChargeKind()};now=ms/2;s.drawUniqueRing();assert.equal(s.uniqueHint.text,'CHARGE 50%');assert(Math.abs(s.arcs.at(-1)[4]-Math.PI/2)<1e-8);now=ms;s.drawUniqueRing();assert.equal(s.uniqueHint.text,'RELEASE');s._snipe=null;s.uniqueCd=3.2;s.drawUniqueRing();assert.equal(s.uniqueHint.text,'4s');s.uniqueCd=0;s.drawUniqueRing();assert.equal(s.uniqueHint.text,'HOLD');}
for(const [hero,path] of [['cocoa','titan'],['momo','spread'],['mint','barrage'],['taro','storm'],['sesame','focus'],['berry','beam'],['yuzu','swarm']]){const s=scene(hero,path);s.updateUniqueHint();assert.equal(s.uniqueHint.text,'TAP');s.refreshFlickerUI();assert.equal(s.flickerBtn.visible,false,'Flicker button removed');}
// Controls fit compact/tall/landscape viewports, both hands and all three sizes; hit areas do not overlap.
for(const [w,h] of [[320,568],[390,844],[844,390]])for(const left of [false,true])for(const size of [0,1,2]){ctx.Save.data.settings={ctrlLeft:left,ctrlSize:size};const s=scene('cocoa','brawler');s.W=w;s.H=h;s.layoutControls();const b=s.flickerBtn,u=s.uniqueBtn,d=s.dashBtn;assert(b.x-b.width/2>=0&&b.x+b.width/2<=w);assert(b.y-b.height/2>=0&&b.y+b.height/2<=h);assert(Math.abs(b.x-u.x)>b.width/2+u.radius+8);assert(d.y-d.radius>u.y+u.radius);assert(s.uniqueHint.y>u.y);}
ctx.Save.data.settings={};
// Real pointer routing toggles without stealing the movement finger, and dispatches hold/release correctly.
{const s=scene('cocoa','brawler'),handlers={};s.input={on:(event,fn)=>handlers[event]=fn};s.setupInput();s.refreshFlickerUI();assert.equal(s.flickerBtn.visible,false);const before=!!s._cocoaFlickerOn;s.toggleCocoaFlicker?.call({character:'mint'});assert.equal(!!s._cocoaFlickerOn,before,'hidden Flicker button cannot be toggled by taps');}
{const s=scene('mint','pierce'),handlers={};s.input={on:(event,fn)=>handlers[event]=fn};let started=0,released=0;s.startSnipeCharge=p=>{started++;s._snipe={id:p.id}};s.releaseSnipe=()=>{released++;s._snipe=null};s.setupInput();handlers.pointerdown({x:s.uniqueBtn.x*2,y:s.uniqueBtn.y*2,id:4});assert.equal(started,1);handlers.pointerup({id:3});assert.equal(released,0);handlers.pointerupoutside({id:3});assert.equal(released,0);handlers.pointerupoutside({id:4});assert.equal(released,1);s.uniqueCd=2;handlers.pointerdown({x:s.uniqueBtn.x*2,y:s.uniqueBtn.y*2,id:4});assert.equal(started,1);}
// New controls participate in HUD hiding and cannot appear for other heroes after resume.
for(const hero of ['cocoa','mint']){const s=scene(hero,'brawler');s.hudList=[s.uniqueBtn,s.uniqueTxt,s.uniqueHint,s.flickerBtn,s.flickerTxt];s.hudVisible(false);assert(s.hudList.every(n=>!n.visible));s.hudVisible(true);assert.equal(s.flickerBtn.visible,false);assert(s.uniqueHint.visible);}
console.log('Combat controls: four hold Uniques, live charge/release/CD, TAP heroes, all viewports/hands/sizes, actual multi-touch routing and HUD visibility passed');

// A second charging finger cannot replace the owner or leak its graphics.
{const s=scene('momo','sniper');let created=0;s.strongestEnemy=()=>null;s.nearestEnemy=()=>null;s.moveDir={x:1,y:0};s.textures={exists:()=>false};s.camWorld=g=>g;s.add={graphics:()=>{created++;return {setDepth(){return this}}}};s.startSnipeCharge({id:1,x:0,y:0});s.startSnipeCharge({id:2,x:0,y:0});assert.equal(s._snipe.id,1);assert.equal(created,1);}
