const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const source=fs.readFileSync('game.js','utf8');
const code=source.slice(source.indexOf('  stopDigPresentation(){'),source.indexOf('  buildRankPerks(){'));
function fixture(kind='chest',hard=false){
 let saves=0,dailies=0,rebuilds=0;const jobs=[],tweens=[],d={shovels:20,depth:7,board:Array.from({length:49},(_,i)=>({c:i===0?kind:'empty',hp:i===0&&hard?2:1,open:false,hard:i===0&&hard}))};
 const Save={data:{threads:0,sugar:0,coreStones:{}},dig:()=>d,save:()=>saves++,threads(){return this.data.threads;},coreStones:()=>0,scrolls:()=>0,digFreeReady:()=>false,addSugar(n){this.data.sugar+=n;},addCurrency(){}};
 const context={Save,DIG_ITEMS:{empty:{},chest:{emoji:'C',rare:true},thread:{emoji:'T'},ore:{emoji:'O'},gem:{emoji:'L',rare:true},trap:{emoji:'X'},stone_hp:{emoji:'H',stone:'hp',name:'HP',rare:true}},OVERCAP_ON:false,STONE_THREADS:25,DIG_SHOP_DAILY_LIMIT:3,DIG_SHOP_COST:120,SCROLL_PER_PERK:3,UPGRADES:{hp:{name:'HP'}},digThreadAmt:()=>2,rollWeightedCurrency:()=>null,Phaser:{Math:{Between:(a,b)=>Math.floor((a+b)/2)}},Sfx:new Proxy({},{get:()=>()=>{}}),TAU:Math.PI*2,Math:Object.assign(Object.create(Math),{random:()=>.3})};vm.createContext(context);const C=vm.runInContext('class Scene{'+code+'}Scene',context),s=new C();
 function alive(o){if(!o.scene)throw Error("Cannot read properties of undefined (reading 'sys')");}
 function obj(x=0,y=0,key){const o={scene:s,x,y,key,scaleX:1,scaleY:1,list:[],setOrigin(){alive(this);return this;},setDisplaySize(w,h){alive(this);this.scaleX=w/256;this.scaleY=h/256;return this;},setAlpha(){alive(this);return this;},setRotation(){alive(this);return this;},setStrokeStyle(){alive(this);return this;},setScale(x,y=x){alive(this);this.scaleX=x;this.scaleY=y;return this;},setX(x){alive(this);this.x=x;return this;},setAngle(){alive(this);return this;},setText(t){alive(this);this.text=t;return this;},setTexture(){alive(this);return this;},add(v){this.list.push(...(Array.isArray(v)?v:[v]));},removeAll(destroy){if(destroy)this.list.forEach(x=>x.destroy());this.list=[];},destroy(){if(!this.scene)return;this.list.forEach(x=>x.destroy());this.scene=null;},setVisible(){return this;}};for(const name of ['fillStyle','fillRoundedRect','lineStyle','strokeRoundedRect','beginPath','moveTo','lineTo','strokePath','fillTriangle','setPosition'])o[name]=()=>o;return o;}
 const time={now:100,delayedCall(ms,fn){const j={at:this.now+ms,fn,remove(){this.cancelled=true;}};jobs.push(j);return j;}};
 const manager={add(c){const targets=Array.isArray(c.targets)?c.targets:[c.targets],t={targets,stop(){this.stopped=true;}};tweens.push(t);if(c.repeat!==-1)jobs.push({at:time.now+(c.delay||0)+(c.duration||0)*(1+(c.repeat||0))*(c.yoyo?2:1)+(c.hold||0),fn(){if(t.stopped)return;targets.forEach(alive);c.onComplete&&c.onComplete();}});return t;},killTweensOf(targets){const list=Array.isArray(targets)?targets:[targets];tweens.forEach(t=>{if(t.targets.some(x=>list.includes(x)))t.stop();});}};
 Object.assign(s,{W:390,H:844,menuScreen:'dig',menu:obj(),time,tweens:manager,textures:{exists:()=>true},add:{container:obj,image:obj,text:obj,graphics:obj,rectangle:obj,circle:obj},_screenBg(){},_hdrShift:()=>30,_zone(){},menuToast(){},advanceDaily(){dailies++;}});
 const build=s.buildDig;s.buildDig=function(){rebuilds++;return build.call(this);};s.buildDig();
 function run(until=Infinity){let budget=10000;while(budget--){jobs.sort((a,b)=>a.at-b.at);const j=jobs[0];if(!j||j.at>until)break;jobs.shift();time.now=j.at;if(!j.cancelled)j.fn();}assert(budget>0);}
 function leave(){s.menuScreen='hub';s.stopDigPresentation();s.menu.removeAll(true);}
 return {s,d,Save,run,leave,get dailies(){return dailies;},get rebuilds(){return rebuilds;}};
}
for(const kind of ['chest','thread','ore','gem','trap','stone_hp']){const f=fixture(kind);f.s.digCell(0);f.run();assert(f.d.board[0].taken);assert.equal(f.d.shovels,kind==='trap'?18:19);assert.equal(f.dailies,1);assert.equal(f.rebuilds,2);const before=JSON.stringify(f.Save.data);f.s.digResolve(f.d.board[0]);assert.equal(JSON.stringify(f.Save.data),before,'one reward');}
for(const cut of [100,240,600,1100,1600]){const f=fixture();f.s.digCell(0);f.run(cut);f.leave();f.run();assert(f.d.board[0].taken);assert.equal(f.Save.data.threads,8);assert.equal(f.dailies,1);}
const rock=fixture('thread',true);rock.s.digCell(0);rock.run();assert(!rock.d.board[0].open);rock.s.digCell(0);rock.run();assert.equal(rock.d.shovels,18);assert.equal(rock.Save.data.threads,2);
console.log('Dig lifecycle: actual soft/hard/chest/rare/trap flows, destroyed-object guards, Back at five timings, redraw cleanup and exactly-once rewards passed');
