const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('game.js','utf8');
function method(n){const at=source.indexOf('  '+n+'('),tail=source.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);assert(at>=0&&next,n);return source.slice(at,at+1+next.index);}
function block(n,end='\n};'){const at=source.indexOf('const '+n+' =');return vm.runInNewContext(source.slice(at,source.indexOf(end,at)+end.length)+'\n'+n);}
const defs=block('ASSET_SHEETS'),balance=block('BALANCE');
const ids=['c21_crown_sapling','mini_jelly','c3_elite','feast_target','mimic_chest'];
const special=new Set(ids.map(id=>id+'_animated')),clips=new Map();
const anims={exists:k=>clips.has(k),generateFrameNumbers:(k,{start,end})=>Array.from({length:end-start+1},(_,i)=>({key:k,frame:start+i})),create(c){clips.set(c.key,c);}};
const at=source.indexOf('function registerEnemyActionAnimations('),last=source.indexOf('const ASSET_SHEETS =',at);
const register=vm.runInNewContext(source.slice(at,last)+'\nregisterEnemyActionAnimations',{ASSET_SHEETS:defs});
for(const key of special)anims.create({key:key+'_walk'});
register({anims,textures:{exists:()=>true}});
const names=['applySpecialEnemyArt','stopEnemyPresentation','resetEnemyPresentation','enemyAction','tickEnemyPresentation','spawnElite','spawnEnemy','antArtKey','drainArtKey','fireArtKey','iceArtKey','stage5ArtKey','chapter3ArtKey','canopyArtKey','myceliumArtKey','nectarArtKey','tickFeast','recipeOnKill','awakenMimic','wardenAct','touchEnemy','playEnemyDeath','chapter2DeathGhost'];
const curves=(i,a,t=1.18)=>i<a.length?a[i]:a.at(-1)*t**(i-a.length+1);
const killBody=method('killEnemy'),rewardStart=killBody.indexOf('if(e._mimic){'),rewardEnd=killBody.indexOf('\n',rewardStart);const mimicReward=killBody.slice(rewardStart,rewardEnd);
const Scene=vm.runInNewContext('class Scene{'+names.map(method).join('\n')+'\nmimicReward(e){'+mimicReward+'}\n}Scene',{Math,Phaser:{Math:{FloatBetween:a=>a,Between:a=>a}},stageCurveValue:curves,ASSET_SHEETS:defs,BALANCE:balance,TAU:Math.PI*2,FEAST_FIRST:6,FEAST_EVERY:16,FEAST_LIFE:22,FEAST_SHARE:.15,HUNGER_PER_KILL:.25,Sfx:new Proxy({},{get:()=>()=>{}})});
const widths={e_tank:62,chest:48,delve10_minijelly:256};
function mob(x,y,key,frame=0){const e={active:true,x,y,scaleX:1,scaleY:1,body:{isCircle:false,offset:{x:0,y:0},velocity:{x:0,y:0},reset(x,y){e.x=x;e.y=y;}},anims:{isPlaying:false,isPaused:false,stop(){this.isPlaying=false;this.isPaused=false;},pause(){this.isPaused=true;},resume(){this.isPaused=false;}},setTexture(k,f=0){this.texture={key:k};this.width=this.height=defs[k]?.frame||widths[k]||128;this.frame=f;return this;},setFrame(f){this.frame=f;return this;},setActive(v){this.active=v;return this;},setVisible(){return this;},setPosition(x,y){this.x=x;this.y=y;return this;},setCircle(r,x,y){this.body.isCircle=true;this.body.radius=r;this.body.offset={x,y};return this;},setScale(x,y=x){this.scaleX=x;this.scaleY=y;return this;},setVelocity(x,y){this.body.velocity={x,y};return this;},clearTint(){this.tint=null;return this;},setTint(v){this.tint=v;return this;},setDepth(){return this;},setFlipX(){return this;},setAlpha(){return this;},play(k){this.clip=k;this.anims.isPlaying=true;return this;}};e.body.setCircle=(...v)=>e.setCircle(...v);return e.setTexture(key,frame);}
function fx(){return {setTint(){return this;},setDisplaySize(){return this;},setAlpha(){return this;},setDepth(){return this;},destroy(){}};}
function fixture(si=5,painted=true){const s=new Scene(),created=[],tweens=[],chests=[];let recycled=null;
 Object.assign(s,{stageIndex:si,waveIndex:0,W:390,H:844,viewZoom:1,player:{x:0,y:0,iframe:0},anims,textures:{exists:k=>painted||!special.has(k)},enemies:{getFirstDead:()=>recycled,create(...a){const e=mob(...a);created.push(e);return e;},getFirstAlive:()=>created.find(e=>e.active),countActive:()=>created.filter(e=>e.active).length},getPowerGuide:()=>({enemyHp:1,enemyDmg:1}),killPowerMul:()=>1,diffMul:()=>({hp:1,dmg:1}),newbieEase:()=>1,clearObjectiveTargetFx(){},camWorld:o=>o,vfxSpawnPoof(){},add:{image:fx},showBanner(){},screenShake(){},screenFlash(){},burst(){},tweens:{add(c){tweens.push(c);},killTweensOf(){}},dist:(x,y,a,b)=>Math.hypot(x-a,y-b),recipeHungerGoal:()=>100,spawnChest:(...a)=>chests.push(a),consumeShell:()=>true});
 s.player.setVelocity=()=>{};return {s,created,tweens,chests,recycle:e=>recycled=e};
}
function stats(e){return [e.hp,e.maxhp,e.spd,e.dmg,e.xp,e.isElite];}
function physical(e){const sc=e.baseScale,b=e.body;return [e.width*sc,b.radius*sc,(b.radius+b.offset.x-e.width/2)*sc,(b.radius+b.offset.y-e.height/2)*sc];}
function close(a,b){for(let i=0;i<a.length;i++)assert(Math.abs(a[i]-b[i])<1e-8,[a,b]);}
for(const si of [5,10,11,12,13,14]){const old=fixture(si,false).s.spawnElite(),e=fixture(si).s.spawnElite();assert.deepEqual(stats(e),stats(old));close(physical(e),physical(old));assert.equal(e.texture.key,si===5?'c21_crown_sapling_animated':'c3_elite_animated');assert.equal(e._enemyRestFrame,0);assert.equal(old.texture.key,si===5?'ch2_enemy_atlas':'e_tank');assert.equal(old._enemyRestFrame,si===5?6:0);}
for(const si of [0,1,4,5,6,8,10,14]){const a=fixture(si),b=fixture(si,false);a.s._feastT=b.s._feastT=0;a.s.tickFeast(.1);b.s.tickFeast(.1);const e=a.s._feastOn,old=b.s._feastOn;assert.deepEqual(stats(e),stats(old));close(physical(e),physical(old));assert.equal(e.texture.key,'feast_target_animated');assert.equal(e._feastLife,22);assert.equal(a.s._feastT,16);e.setVelocity(100,0);a.s.tickEnemyPresentation(e,.016);assert.equal(e.clip,'feast_target_animated_walk');e.setPosition(0,100);a.s.tickFeast(1);a.s.tickEnemyPresentation(e,.016);assert.equal(e.clip,'feast_target_animated_flee');assert.equal(e._feastLife,21);assert(!defs.feast_target_animated.actions.attack);a.s.touchEnemy(a.s.player,e);assert.notEqual(e._enemyAction?.state,'attack');e.frozen=1;a.s.tickEnemyPresentation(e,2);assert(e.anims.isPaused);e.frozen=0;a.s.tickEnemyPresentation(e,.016);assert(!e.anims.isPaused);a.s.recipeMode=true;a.s.mode='wave';a.s._hunger=0;a.s.recipeOnKill(e);assert.equal(a.s._hunger,15);assert.equal(a.s._feastOn,null);assert.equal(e._feast,false);assert.equal(a.s._feastT,8);}
{const f=fixture();f.s._feastT=0;f.s.tickFeast(.1);const e=f.s._feastOn;e._feastLife=.1;f.s.tickFeast(.2);assert(e._fleeing);assert(!e._feast);assert.equal(f.s._feastOn,null);f.tweens.at(-1).onComplete();assert(!e.active);f.recycle(e);const ordinary=f.s.spawnElite();assert.equal(ordinary,e);assert(!ordinary._feast);assert(!ordinary._fleeing);assert(!ordinary._huntFlee);assert.equal(ordinary.texture.key,'c21_crown_sapling_animated');}
for(const painted of [true,false]){const f=fixture(10,painted);const baseline=f.s.spawnElite().maxhp;f.s.awakenMimic(20,30,'gold');const e=f.created.at(-1);assert.equal(e.hp,baseline*2.6);assert.equal(e.spd,48*1.6);assert.equal(e.dmg,Math.round(f.created[0].dmg*1.15));assert.equal(e._mimic,'gold');assert.equal(e.frozen,.9);assert.equal(e.texture.key,painted?'mimic_chest_animated':'chest');assert.equal(e._enemyArtKey,e.texture.key);close(physical(e),[64,26.88,0,0]);assert.equal(f.tweens.length,painted?0:1);e.frozen=0;f.s.touchEnemy(f.s.player,e);if(painted)assert.equal(e.clip,'mimic_chest_animated_attack');f.s.mimicReward(e);assert.deepEqual(f.chests,[[20,30,'mini']]);assert.equal(f.s._nextChestTier,'gold');assert(f.s._noMimicNext);assert.equal(e._mimic,null);f.s.mimicReward(e);assert.equal(f.chests.length,1);}
{const f=fixture(5);f.s.enemies.create=()=>null;f.s.enemies.getFirstAlive=()=>null;f.s.awakenMimic(1,2,'silver');assert.deepEqual(f.chests,[[1,2,'mini']]);assert.equal(f.s._nextChestTier,'silver');assert(f.s._noMimicNext);}
for(const painted of [true,false]){const f=fixture(0,painted),b={x:100,y:200,hp:500,maxhp:1000,dmg:20,_dv:{split:false}};f.s.dvPose=()=>{};f.s.wardenAct(b);assert.equal(f.created.length,3);assert(b._dv.split);assert.equal(b._dv.cd,1.6);for(const e of f.created){assert.equal(e.texture.key,painted?'mini_jelly_animated':'delve10_minijelly');assert.equal(e.hp,50);assert.equal(e.dmg,9);assert.equal(e.spd,36);assert.equal(e.xp,4);assert(e.isElite);close(physical(e),[92.16,25.2,0,4.32]);assert.equal(e._enemyArtKey,e.texture.key);}b._dv.act='unused';/* split flag guards the same threshold */}
{const f=fixture(0);const original=f.s.textures.exists;f.s.textures.exists=k=>k!=='delve10_minijelly'&&original(k);f.s.dvPose=()=>{};f.s.wardenAct({x:0,y:0,hp:1,maxhp:100,dmg:10,_dv:{split:false}});assert(f.created.every(e=>e.texture.key==='mini_jelly_animated'));}
for(const id of ids){const f=fixture(),e=f.s.spawnElite();if(id==='mini_jelly'){e.setTexture('delve10_minijelly');e.baseScale=.36;e.setCircle(70,58,70);}f.s.applySpecialEnemyArt(e,id+'_animated');e.setVelocity(60,0);f.s.tickEnemyPresentation(e,.016);assert.equal(e.clip,id+'_animated_walk');f.s.enemyAction(e,'hurt',120);assert.equal(e.clip,id+'_animated_hurt');e.frozen=1;f.s.tickEnemyPresentation(e,2);assert.equal(e._enemyActionT,.12);e.frozen=0;f.s.tickEnemyPresentation(e,.13);assert.equal(e._enemyAction,null);let ghost,complete;f.s.fxOk=()=>true;f.s.trackArtVfx=o=>o;f.s.add.sprite=()=>ghost={setScale(){return this;},setFlipX(){return this;},setDepth(){return this;},once(n,fn){complete=fn;},play(k){assert.equal(k,id+'_animated_death');},destroy(){this.destroyed=true;}};f.s.playEnemyDeath(e);complete();assert(ghost.destroyed);let extra=0;f.s.add.image=()=>{extra++;return fx();};f.s.chapter2DeathGhost(e);assert.equal(extra,0);f.recycle(e);f.s.spawnElite();assert.equal(e._enemyAction,null);assert(!e._mimic);assert(!e._feast);}
const packing=JSON.parse(fs.readFileSync('assets/incoming/elite_summons/PACKING.json','utf8'));
for(const id of ids){const key=id+'_animated',png=fs.readFileSync('assets/incoming/elite_summons/'+id+'_sheet.png');assert.equal(png.readUInt32BE(16),1024);assert.equal(png.readUInt32BE(20),1024);assert.equal(png[25],6);const b=fs.readFileSync(defs[key].url);assert.equal(b.toString('ascii',12,16),'VP8L');const dim=b.readUInt32LE(21);assert(dim&(1<<28));assert.equal((dim&0x3fff)+1,1024);assert.equal(((dim>>>14)&0x3fff)+1,1024);for(const [x,y,w,h] of packing[id].bounds){assert(x>=10&&y>=10&&x+w<=246);assert.equal(y+h,236);}assert.equal(packing[id].sourceFrameOrder.length,16);assert.deepEqual(Array.from(clips.get(key+'_death').frames,f=>f.frame),[14,15]);}
assert.equal(clips.get('feast_target_animated_flee').repeat,-1);
const loadStart=source.indexOf('const STAGE_SHEETS='),loadEnd=source.indexOf('function bootKeepAudio(',loadStart);
const loads=vm.runInNewContext(source.slice(loadStart,loadEnd)+'\n({stages:STAGE_SHEETS,stageCritical})');
assert(loads.stages[5].includes('c21_crown_sapling_animated'));for(let i=10;i<15;i++)assert(loads.stages[i].includes('c3_elite_animated'));
for(const k of ['mini_jelly_animated','feast_target_animated']){assert(!loads.stageCritical(k,defs[k].url,'momo',false));assert(loads.stageCritical(k,defs[k].url,'momo',true));}
console.log('Elite/special: actual spawns, world collider parity, fallback, Feast flee/expiry/Hunger, Mimic conversion/bite, Warden three-way split, freeze/pool/death and lazy loading passed');
