const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const s=fs.readFileSync('game.js','utf8'),block=(a,b)=>s.slice(s.indexOf(a),s.indexOf(b));function method(n){const at=s.indexOf('  '+n+'('),tail=s.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);assert(at>=0&&next,n);return s.slice(at,at+1+next.index);}
const baseline=JSON.parse(fs.readFileSync('tests/fixtures/presentation-art-baseline.json'));
const ctx={Phaser:{BlendModes:{NORMAL:0}},COLORS:{pink:1},STAGES:Array.from({length:15},(_,i)=>({name:'Stage '+(i+1),tint:1})),Sfx:{result(){},stopCraft(){}}};vm.createContext(ctx);vm.runInContext(block('function epilogueLayout(','const STORY_REACTIONS =')+block('const ASSET_FX = {','const ASSET_AUDIO = {'),ctx);const a=vm.runInContext('({epilogueLayout,STAGE_EPILOGUE,ASSET_FX})',ctx);
assert.deepEqual(JSON.parse(JSON.stringify(a.STAGE_EPILOGUE)),baseline.epilogues,'story wording preserved');assert.equal(method('gainCharExp').trimEnd(),baseline.charExp.trimEnd());assert.equal(method('checkUniqueAutoUpgrade').replace("(u.tiers||UNIQUE_TIERS[(CHARACTERS[this.character]||CHARACTERS.momo).unique])[target]","UNIQUE_TIERS[(CHARACTERS[this.character]||CHARACTERS.momo).unique][target]").replace("this.playGrowthWorld?.('unlock');",'').trimEnd(),baseline.uniqueUpgrade.trimEnd());
const Scene=vm.runInContext('class Scene{'+['resultBackdrop','showStageEpilogue','playGrowthWorld','playSummaryGrowth','stopSummaryPresentation','animateSummaryRewards','clearArtVfx','trackArtVfx'].map(method).join('\n')+'\n}Scene',ctx);
function item(kind,x,y,key){const o={kind,x,y,key,active:true,events:{},setOrigin(){return this},setDisplaySize(w,h){this.width=w;this.height=h;return this},setAlpha(a){this.alpha=a;return this},setTint(t){this.tint=t;return this},setBlendMode(m){this.blend=m;return this},once(e,fn){this.events[e]=fn;return this},play(k){this.playing=k;return this},destroy(){this.active=false;this.events.destroy?.();}};return o;}
for(const [W,H] of [[390,844],[320,568],[844,390]])for(let index=0;index<15;index++)for(const available of [true,false]){
 const scene=new Scene(),objects=[];const make=(kind)=>(x,y,key)=>{const o=item(kind,x,y,key);objects.push(o);return o;};const L=a.epilogueLayout(W,H);Object.assign(scene,{W,H,stageIndex:index,physics:{pause(){}},player:{setVelocity(){}},over:{removeAll(){},add(){},setVisible(){}},textures:{exists:()=>available},add:{rectangle:make('rectangle'),image:make('image'),text:make('text')},tweens:{add(){}},screenFlash(){},_endBtn(box,x,y,w,h){return{x:x-w/2,y:y-h/2,w,h}},showStageSummary(last){this.summary=last;this.state='summary';}});
 scene.showStageEpilogue(index===14);assert.equal(scene.state,'epilogue');assert(objects.some(o=>o.key===a.STAGE_EPILOGUE[index].body));assert(objects.some(o=>o.key===a.STAGE_EPILOGUE[index].why));assert(objects.some(o=>o.key===(available?'epilogue_s'+(index+1):'vfx_glow')));assert(L.artX-L.artW/2>=0&&L.artX+L.artW/2<=W);assert(L.artY-L.artH/2>=0&&L.artY+L.artH/2<=H);const z=scene._epilogueBtns[0];assert(z.x>=0&&z.y>=0&&z.x+z.w<=W&&z.y+z.h<=H);z.fn();assert.equal(scene.summary,index===14);scene.summary=null;z.fn();assert.equal(scene.summary,null,'callback state guard');scene.riftMode=true;scene.showStageEpilogue(false);assert.equal(scene.summary,false);
 scene._coverImage=(x,y,w,h,key)=>item('cover',x,y,key);assert.equal(scene.resultBackdrop('result_defeat').kind,available?'cover':'rectangle');
}
let spawned=[],destroyed=0,scene=new Scene();Object.assign(scene,{W:390,H:844,state:'play',player:{x:123,y:456,hp:90},time:{now:1000},textures:{exists:()=>true},spawnFxAnim(key,x,y,opt){const o=item('world',x,y,key);spawned.push({...opt,key,x,y,obj:o});return o;},tweens:{killTweensOf(){}},add:{sprite:(x,y,key)=>item('sprite',x,y,key)},anims:{exists:()=>false,create(){},generateFrameNumbers:()=>[]},camUI:o=>o,over:{add(){}}});
assert(scene.playGrowthWorld('levelup'));assert(scene.playGrowthWorld('levelup'));assert.equal(spawned.length,1);assert.equal(spawned[0].normal,true);assert.equal(spawned[0].y,444);scene.time.now=1600;scene.playGrowthWorld('unlock');assert.equal(spawned.length,2);scene.clearArtVfx();assert(spawned.every(x=>!x.obj.active));assert.equal(scene._growthVfxAt,null);assert.equal(scene.player.hp,90);scene.textures.exists=()=>false;assert.equal(scene.playGrowthWorld('levelup'),false);scene.textures.exists=()=>true;
scene.playSummaryGrowth('mastery');const fx=[...scene._summaryGrowthVfx][0];assert.equal(fx.blend,0);assert.equal(fx.playing,'growth_mastery');fx.events.animationcomplete();assert(!fx.active&&scene._summaryGrowthVfx.size===0);scene.playSummaryGrowth('levelup');const cancelled=[...scene._summaryGrowthVfx][0];scene.stopSummaryPresentation();assert(!cancelled.active);assert.equal(scene._summaryGrowthVfx.size,0);
const packing=JSON.parse(fs.readFileSync('assets/incoming/ending_growth/PACKING.json'));assert.equal(Object.keys(packing.epilogues).length,15);for(const key of ['growth_levelup','growth_mastery','growth_unlock']){const d=a.ASSET_FX[key];assert.equal(d.frames,8);assert.equal(d.rate,12);assert(fs.existsSync(d.url));const png=fs.readFileSync('assets/incoming/ending_growth/'+key+'_sheet.png');assert.equal(png.readUInt32BE(16),2048);assert.equal(png.readUInt32BE(20),256);assert.equal(png[25],6);const webp=fs.readFileSync(d.url);assert.equal(webp.toString('ascii',12,16),'VP8L');assert(webp.readUInt32LE(21)&0x10000000);assert.equal(packing.growth[key].uniqueFrames,8);}
for(let index=0;index<15;index++)assert(fs.existsSync('assets/story/epilogues/epilogue_s'+(index+1)+'.webp'));for(const key of ['result_victory','result_defeat'])assert(fs.existsSync('assets/ui/results/'+key+'.webp'));
assert(s.includes("this.playGrowthWorld?.('unlock');"));assert(s.includes("this.resultBackdrop(this._quitSummary?'result_defeat':'result_victory')"));console.log('Ending/growth art: all 15 unchanged epilogues and three viewports, Rift/fallback/button guards, original EXP/Unique ranks, NORMAL effects, throttle, shutdown/cancellation and alpha-sheet contracts passed');
