const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('game.js','utf8');
function method(n){const at=src.indexOf('  '+n+'(');assert(at>=0,n);const next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(src.slice(at+1));return src.slice(at,at+1+next.index);}
let rng=1;const math=Object.create(Math);math.random=()=>rng;
const ctx={Math:math,Sfx:{heal(){},magnet(){}}};vm.createContext(ctx);
const names=['usesStoryBudget','fieldDropState','healingItemPower','storyFieldDrops','storyOnKillHealing','dropHeal','collectHeal','spawnVac','collectVac'];
const Scene=vm.runInContext('class Scene{'+names.map(method).join('\n')+'\n}Scene',ctx);
function item(x=0,y=0){return {x,y,active:true,body:{enable:true,setAllowGravity(){}},setActive(v){this.active=v;return this;},setVisible(){return this;},setPosition(x,y){this.x=x;this.y=y;return this;},setDepth(){return this;},setVelocity(x,y){this.velocity=[x,y];return this;}};}
function group(){const pool=[];return {pool,children:{iterate:f=>pool.forEach(f)},countActive:()=>pool.filter(x=>x.active).length,getFirstDead:()=>pool.find(x=>!x.active),create(x,y){const o=item(x,y);pool.push(o);return o;}};}
function scene(){const s=new Scene();Object.assign(s,{player:{hp:40,maxhp:100,x:10,y:10},elapsed:0,heals:group(),vacs:group(),orbs:group(),recipeHas:()=>false,pactHealMul:()=>1,tweens:{add(){},killTweensOf(){}},textures:{exists:()=>false},anims:{exists:()=>false},camWorld(){},showPickupCue(){},hidePickupCue(){},jelly(){},popHeal(x,y,n){this.healShown=n;},fireRecipes(){this.triggers=(this.triggers||0)+1;},burst(){},vfxCollectSparkle(){},floatText(){}});return s;}
// Full/forbidden healing does not waste the heart or trigger healing recipes.
{const s=scene(),h=s.dropHeal(1,2);s.player.hp=100;s.collectHeal(null,h);assert(!h.active);assert.equal(s.player.hp,100);const h2=s.dropHeal(0,0,'mini');s.player.hp=30;s.collectHeal(null,h2);assert(!h2.active);assert.equal(s.player.hp,48);assert.equal(s.healShown,18);}
for(const [effect,missing,expected] of [[2,80,35],[1,4,4],[.5,80,9]]){const s=scene();s.player.hp=100-missing;s.player.healEffect=effect;const h=s.dropHeal(0,0);s.collectHeal(null,h);assert.equal(s.healShown,expected);assert.equal(s.player.hp,100-missing+expected);}
// All sources share stage quota/cooldown/ground slots. Mini may bypass only cooldown.
{const s=scene();const a=s.dropHeal(0,0);assert.equal(s.dropHeal(0,0),null);const b=s.dropHeal(0,0,'mini');assert(b);assert.equal(s.dropHeal(0,0,'mini'),null);a.active=b.active=false;s.elapsed=25;assert(s.dropHeal(0,0));s.elapsed=50;assert(s.dropHeal(0,0));s.heals.pool.forEach(h=>h.active=false);s.elapsed=100;assert.equal(s.dropHeal(0,0,'mini'),null);assert.equal(s.fieldDropState().hearts,4);}
{const s=scene();s.heals.create=()=>null;assert.equal(s.dropHeal(0,0),null);assert.equal(s.fieldDropState().hearts,0);s.vacs.create=()=>null;s.fieldDropState().magnetProgress=70;assert.equal(s.spawnVac(0,0),null);assert.equal(s.fieldDropState().magnetProgress,70);assert.equal(s.fieldDropState().magnets,0);}
// No normal heart and no guaranteed mini magnet. Bad luck protection requires earned ground EXP.
{const s=scene();rng=1;for(let k=0;k<100;k++)s.storyFieldDrops({x:0,y:0});assert.equal(s.heals.pool.length,0);assert.equal(s.vacs.pool.length,0);s.orbs.pool.push(item());s.orbs.pool[0].value=20;s.storyFieldDrops({x:0,y:0});assert.equal(s.vacs.countActive(),1);assert.equal(s.fieldDropState().magnetProgress,0);s.storyFieldDrops({x:0,y:0,isMini:true});assert.equal(s.fieldDropState().magnets,1);assert.equal(s.heals.countActive(),1);}
// Magnet stages: 1 ground slot, 50 seconds, 2 total; always collectable even with no orbs.
{const s=scene();let v=s.spawnVac(0,0);assert(v);assert.equal(s.spawnVac(0,0),null);s.collectVac(null,v);assert(!v.active);s.fieldDropState().magnetProgress=70;s.elapsed=49;assert.equal(s.spawnVac(0,0),null);assert.equal(s.fieldDropState().magnetProgress,70);s.elapsed=50;v=s.spawnVac(5,6);assert(v);assert.equal(v.x,5);assert(v.body.enable);const o=item();o.value=7;s.orbs.pool.push(o);s.collectVac(null,v);assert(o._vac);assert.equal(o.value,7);s.elapsed=200;assert.equal(s.spawnVac(0,0),null);}
// Dense kills cannot turn healing gear into unlimited recovery. Hungry Pact forbids items only.
{const s=scene();s.player.hp=1;s.player.lifesteal=3;s.player.lifeOnKill=2;for(let k=0;k<200;k++)s.storyOnKillHealing();assert.equal(s.player.hp,4);s.elapsed=.99;s.storyOnKillHealing();assert.equal(s.player.hp,4);s.elapsed=1;s.storyOnKillHealing();assert.equal(s.player.hp,7);s.recipeHas=()=>true;s.elapsed=2;s.storyOnKillHealing();assert.equal(s.player.hp,7);s.recipeHas=()=>false;s.pactHealMul=()=>0;s.storyOnKillHealing();assert.equal(s.player.hp,7);s.pactHealMul=()=>1;s.player.healEffect=0;s.storyOnKillHealing();assert.equal(s.player.hp,10);assert.equal(s.dropHeal(0,0),null);}
// Special modes keep old drop frequency and heart amount; full HP preservation is shared QoL.
for(const flag of ['recipeMode','riftMode','bossRush','endlessMode','_inTutorial']){const s=scene();s[flag]=true;for(let k=0;k<6;k++){assert(s.dropHeal(0,0));assert(s.spawnVac(0,0));}s.collectHeal(null,s.heals.pool[0]);assert.equal(s.player.hp,64);assert.equal(s._fieldDrops,undefined);}
assert(method('startStage').includes('this._fieldDrops=null;this._storyKillHeal=null;this._lifeOnKillCd=0'));
assert(method('killEnemy').includes('this.storyFieldDrops(e)'));assert(method('killEnemy').includes('this.storyOnKillHealing()'));
assert(method('breakCrate').includes('this.usesStoryBudget?.()?0.20:0.28'));
console.log('P2 pickups: actual drop/collection/director methods, healing restrictions, full HP, effective heal, shared quotas, cooldowns, pooling failures, earned-EXP magnet, bad luck protection, dense-kill recovery, stage resets and special-mode isolation passed');
