const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),s=fs.readFileSync('game.js','utf8');
function method(n){const a=s.indexOf('  '+n+'(',s.indexOf('class Game extends')),m=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(s.slice(a+1));return s.slice(a,a+1+m.index);}
const item={uid:'reward',slot:'weapon'},data={gearTut:1,gearItems:[item]},events=[],ctx={Save:{data,isGearEquipped:()=>false,gearItem:()=>item,equippedGearItem:()=>item,save(){events.push('save');}},GEAR_ALL:[],GACHA_LEVELS:[{cost:1}]};vm.createContext(ctx);const C=vm.runInContext('class T{'+method('applyGearTut')+'\n}\nT',ctx),t=new C();Object.assign(t,{W:390,H:844,state:'menu',menuScreen:'gear',tapZones:[{gearItemUid:'reward',x:14,y:100,w:100,h:100,fn(){events.push('detail');}}],add:{container:()=>({add(){}}),text:()=>({setOrigin(){return this;}})},menu:{add(){}},drawSpotlight(_c,_x,_y,_w,_h,label){this.label=label;},menuToast(){},time:{delayedCall(){}},buildMenuScreen(){events.push('rebuild');}});
t.applyGearTut();assert.equal(t.label,'Open item details');t.tapZones[0].fn();assert.equal(data.gearTut,1);assert.equal(events.at(-1),'detail');
t.menuScreen='gearDetail';t.tapZones=[{x:14,y:500,w:90,h:44,fn:function(){/* equipGearInstance */events.push('equip');}}];t.applyGearTut();t.tapZones[0].fn();assert.equal(data.gearTut,2);assert.equal(events.at(-1),'equip');
t.menuScreen='gear';t.gearSelectedUid='reward';t.tapZones=[{gearItemUid:'reward',x:14,y:100,w:100,h:100,fn(){events.push('detail');}}];t.applyGearTut();t.tapZones[0].fn();assert.equal(data.gearTut,2);
t.menuScreen='gearDetail';t.tapZones=[{x:14,y:500,w:90,h:44,fn:function(){/* menuScreen='craft' */events.push('craft');}}];t.applyGearTut();t.tapZones[0].fn();assert.equal(data.gearTut,3);assert.equal(events.at(-1),'craft');
assert(s.includes("if(Save.data.gearTut===0)this._gearTools=true"));
console.log('Equipment tutorial: opening details does not skip Equip/Craft, progression remains sequential and tutorial gacha is exposed');
