const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('game.js','utf8');function method(n){const start=src.indexOf('  '+n+'(',src.indexOf('class Game extends')),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(src.slice(start+1));assert(start>=0&&next);return src.slice(start,start+1+next.index);}
const defs={power:{label:'Very long increased chocolate weapon damage modifier',kind:'prefix',emoji:'',fmt:v=>'+'+v+'%'},life:{label:'Life recovered after a kill',kind:'suffix',emoji:'',fmt:v=>'+'+v}};
const base={id:'blade',name:'Long named chocolate blade of the ancient garden',desc:'A unique effect with a long description that must wrap without covering the next row.',unique:true};
const eq={uid:'eq',baseId:'blade',slot:'weapon',itemLevel:40,enhanceLv:2,grade:'rare',affixes:[{id:'power',v:10,t:5},{id:'life',v:2,t:4}]},sel={uid:'sel',baseId:'other',slot:'weapon',itemLevel:50,grade:'epic',affixes:[{id:'power',v:20,t:2}]};
const other={id:'other',name:'New sword',desc:'',unique:false};
const context={GEAR_ALL:[base,other],affixDef:id=>defs[id],ensureImplicit:()=>null,implicitDef:()=>null,implicitText:()=>'',IMPLICIT_TIER:{},IMPLICIT_COLOR:{},weaponLocalMod:()=>false,gearBaseStatText:()=> 'ATK 12–18',gearStatText:(_r,v)=>String(v),gearCompareRows:()=>[{key:'attack',label:'ATK',from:10,to:15,delta:5}],gearSetCompareText:()=>'',Save:{data:{},gearItem:id=>[eq,sel].find(x=>x.uid===id),equippedGearItem:()=>eq,gearItemsForSlot:()=>[eq,sel]}};vm.createContext(context);const C=vm.runInContext('class Test{'+['drawGearMods','modCompareRows','drawModCompare','buildGearCompare'].map(method).join('\n')+'}\nTest',context);
function scene(w,h){const s=new C(),objects=[],zones=[];const g=()=>new Proxy({},{get:(_t,k)=>k==='text'?undefined:()=>g()});Object.assign(s,{W:w,H:h,gearSlot:'weapon',gearSelectedUid:'sel',menu:{removeAll(){objects.length=0;zones.length=0;},add(x){objects.push(...(Array.isArray(x)?x:[x]));},setVisible(){}},add:{graphics:g,text(x,y,text,style){const size=parseFloat(style.fontSize),limit=style.wordWrap?.width||1e6,o={x,y,text:String(text),height:Math.ceil(String(text).length*size*.55/limit)*(size+3),width:Math.min(limit,String(text).length*size*.55),setOrigin(){return this;}};return o;}},_zone(x,y,w,h,fn){zones.push({x,y,w,h,fn});},_screenBg(){},buildMenuScreen(){this.rebuilt=true;}});return {s,objects,zones};}
for(const [w,h] of [[320,568],[390,844],[844,390]]){
 const {s,objects,zones}=scene(w,h);const before=JSON.stringify([eq,sel]);let end=s.drawGearMods(eq,100,w);assert(end>100);assert(objects.some(o=>o.text?.includes(defs.power.label)));assert(objects.some(o=>o.text?.includes(defs.life.label)));assert(objects.some(o=>o.text?.includes(base.desc)));
 objects.length=0;s.drawGearMods({...sel,affixes:[]},100,w);assert(objects.some(o=>o.text==='No mods on this item'));
 objects.length=0;s._cmpBase=context.gearCompareRows();end=s.drawModCompare(eq,sel,false,100,w);assert(objects.some(o=>o.text==='INCREASE · +10%'));assert(objects.some(o=>o.text==='LOST'));assert(objects.some(o=>o.text==='Selected: —'));assert(objects.some(o=>o.text==='BASE · ATK'));
 for(const o of objects.filter(o=>o.text))assert(o.x>=14&&o.x+o.width<=w-14&&o.y+o.height<end,'wrapped comparison text fits panel');
 s.buildGearCompare();assert(objects.some(o=>o.text==='EQUIPPED'));assert(objects.some(o=>o.text==='SELECTED'));assert(zones.every(z=>z.x>=0&&z.x+z.w<=w));zones[0].fn();assert.equal(s.gearSelectedUid,'eq');assert(s.rebuilt);s.buildGearCompare();assert(objects.some(o=>o.text?.startsWith('This item is already equipped')));assert(objects.some(o=>o.text?.includes(defs.life.label)));assert.equal(JSON.stringify([eq,sel]),before,'viewing/cycling does not modify items');
}
assert(src.includes("y=this.drawGearMods(selected,y,w)"));assert(src.includes("Compare with equipped  ›"));assert(src.includes("else if(s==='gearCompare')this.buildGearCompare()"));assert(!src.includes('affN=0'));
console.log('Equipment mods: equipped/selected/no mods, full prefix/suffix/unique lines, wrapped comparisons, lost/increased values and item navigation passed');
