const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),s=fs.readFileSync('game.js','utf8');
const a=s.indexOf('function gearBrowseItems('),b=s.indexOf('function gearStatText(',a),ctx={};vm.createContext(ctx);const browse=vm.runInContext(s.slice(a,b)+'\ngearBrowseItems',ctx);
const items=[{uid:'a',baseId:'sword',grade:'rare',acquiredAt:10,itemLevel:70,enhanceLv:2,isNew:true,affixes:[{id:'life'}]},{uid:'b',baseId:'sword',grade:'legend',acquiredAt:20,itemLevel:30,enhanceLv:5,craftedAt:12,affixes:[{id:'damage'}]},{uid:'c',baseId:'sword',grade:'epic',acquiredAt:30,itemLevel:50,favorite:true,affixes:[{id:'life'}]},{uid:'d',baseId:'weapon_none',grade:'start'}];
const before=JSON.stringify(items),ids=o=>Array.from(browse(items,o),it=>it.uid);
assert.deepEqual(ids({sort:'newest'}),['c','b','a']);assert.deepEqual(ids({sort:'level'}),['a','c','b']);assert.deepEqual(ids({sort:'rarity'}),['b','c','a']);assert.deepEqual(ids({sort:'enhance'}),['b','a','c']);
assert.deepEqual(ids({filter:'new'}),['a']);assert.deepEqual(ids({filter:'crafted'}),['b']);assert.deepEqual(ids({filter:'favorite'}),['c']);assert.deepEqual(ids({mod:'life',sort:'level'}),['a','c']);assert.deepEqual(ids({mod:'damage',filter:'favorite'}),[]);assert.equal(JSON.stringify(items),before);
function method(n){const at=s.indexOf('  '+n+'(',s.indexOf('class Game extends')),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(s.slice(at+1));return s.slice(at,at+1+next.index);}
const events=[],c={Save:{markGearSeen:id=>events.push(['seen',id])}};vm.createContext(c);const C=vm.runInContext('class T{'+method('openGearDetail')+'}\nT',c),t=new C();t.buildMenuScreen=()=>events.push(['screen',t.menuScreen]);t.openGearDetail(items[0]);assert.equal(t.gearSelectedUid,'a');assert.equal(t.menuScreen,'gearDetail');assert.deepEqual(events,[['seen','a'],['screen','gearDetail']]);assert.equal(JSON.stringify(items),before);
assert(s.includes("else if(s==='gearDetail')this.buildGearDetail()"));assert(s.includes("else if(s==='gearFilter')this.buildGearFilter()"));assert(s.includes("bot-this.H+(this._gearPinned?90:24)"));assert(s.includes("o===this._gearPinned"));
console.log('Equipment browsing: independent filters, mod intersection, all sort orders, source immutability and detail navigation passed');
