const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const src=fs.readFileSync('game.js','utf8');
function method(n){const at=src.indexOf('  '+n+'(');assert(at>=0,n);const tail=src.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);return src.slice(at,at+1+next.index);}
const ctx={Math,TAU:Math.PI*2,WORLD:4000,Phaser:{Math:{Clamp:(v,a,b)=>Math.max(a,Math.min(b,v)),FloatBetween:()=>0},BlendModes:{ADD:1}}};vm.createContext(ctx);vm.runInContext(src.slice(src.indexOf('const STORY_WAVE_PLAN='),src.indexOf('const CHANGELOG =')),ctx);
const names=['huntTargetActive','ensureHuntTarget','spawnObjectiveElite','onWaveObjectiveTargetDown','tickWaveObjective','usesStoryBudget','storyTimedSwarm','storyLiveCap','storyCanSpawn'];
const Scene=vm.runInContext('class Scene{'+names.map(method).join('\n')+'\n}Scene',ctx);
function art(){const o={};for(const n of ['setTint','setDepth','setScale','setAlpha','setBlendMode','setPosition'])o[n]=()=>o;return o;}
function enemy(){const e={x:2200,y:-2200,hp:70,active:true,_fleeing:true,_huntFlee:true,alpha:0,anims:{stop(){}},setAlpha(a){this.alpha=a;return this;},setPosition(x,y){this.x=x;this.y=y;return this;}};for(const n of ['setTexture','setCircle','setScale','clearTint'])e[n]=()=>e;return e;}
function scene(stage=4){const s=new Scene();s.stageIndex=stage;s.waveIndex=3;s.mode='wave';s.state='play';s.waveTimer=50;s.maxLive=40;s.waveObjective={type:'hunt',target:3,progress:0,done:false,color:1};s._storyBudget={spawned:72,quota:72,done:false};s.player={x:0,y:0};s.time={now:0,delayedCall(){throw Error('Hunt must not rely on one-shot timers');}};s.foes=[];s.enemies={countActive:()=>s.foes.filter(e=>e.active).length,children:{iterate:fn=>s.foes.forEach(fn)}};s.attempts=0;s.poolFull=false;
 s.spawnElite=(recycle,objective)=>{assert.equal(recycle,false);assert.equal(objective,true);s.attempts++;if(s.poolFull||!s.storyCanSpawn(true))return null;const e=enemy();s.foes.push(e);return e;};
 Object.assign(s,{add:{image:art},textures:{exists:()=>true},tweens:{killTweensOf(e){e.cancelled=true;},add(){}},camWorld:x=>x,resetEnemyPresentation(){},tickWaveEvent(){},tickBonusChallenge(){},tickHuntCurse(){},renderWaveObjectiveHUD(){},dist:(x,y,a,b)=>Math.hypot(x-a,y-b),completeWaveObjective(){s.waveObjective.done=true;s.mode='waveclear';s.completed=(s.completed||0)+1;}});return s;}
// C1-5 wave4: full live cap -> retry due during upgrades -> recover when play resumes.
{const s=scene();s.foes=Array.from({length:24},()=>({active:true}));s.spawnObjectiveElite();assert.equal(s.attempts,1);assert.equal(s.waveObjective._huntSpawnAt,1000);s.state='levelup';s.time.now=2000;s.ensureHuntTarget();assert.equal(s.attempts,1);s.foes[0].active=false;assert(!s.storyCanSpawn(false));assert(s.storyCanSpawn(true));s.state='play';s.tickWaveObjective(.1);assert(s.huntTargetActive());assert.equal(s._storyBudget.spawned,72);const e=s.foes.find(e=>e._waveObjectiveTarget);assert(e.cancelled&&!e._fleeing);assert.equal(e.alpha,1);assert(Math.abs(e.x)<=1880&&Math.abs(e.y)<=1880);for(let k=0;k<20;k++){s.ensureHuntTarget();s.spawnObjectiveElite();}assert.equal(s.foes.filter(e=>e.active&&e._waveObjectiveTarget).length,1);}
// Actual pool failures retry repeatedly; deleting a target without kill cannot deadlock progress.
{const s=scene();s.poolFull=true;s.ensureHuntTarget();assert.equal(s.attempts,1);s.time.now=999;s.ensureHuntTarget();assert.equal(s.attempts,1);s.time.now=1000;s.ensureHuntTarget();assert.equal(s.attempts,2);s.poolFull=false;s.time.now=2000;s.ensureHuntTarget();assert(s.huntTargetActive());s.foes[0].active=false;s.time.now=2100;s.ensureHuntTarget();assert(s.huntTargetActive());assert.equal(s.waveObjective.progress,0);}
// Three sequential targets, 700ms inter-target delay survives pause; success spawns no fourth target.
for(let stage=0;stage<15;stage++){const s=scene(stage);s.ensureHuntTarget();for(let k=0;k<3;k++){const e=s.foes.find(e=>e.active&&e._waveObjectiveTarget);assert(e);s.onWaveObjectiveTargetDown(e);e.active=false;if(k<2){s.state='levelup';s.time.now+=1000;s.ensureHuntTarget();assert(!s.huntTargetActive());s.state='play';s.tickWaveObjective(.1);assert(s.huntTargetActive());}}assert.equal(s.completed,1);assert.equal(s.waveObjective.progress,3);const n=s.attempts;s.ensureHuntTarget();assert.equal(s.attempts,n);}
// Changing objective/run mode makes the stored retry inert; no old callback can leak.
{const s=scene();s.poolFull=true;s.ensureHuntTarget();s.waveObjective={type:'capture'};s.time.now=5000;s.ensureHuntTarget();assert.equal(s.attempts,1);s.waveObjective={type:'hunt',target:3,progress:0};s.mode='boss';s.ensureHuntTarget();assert.equal(s.attempts,1);}
console.log('Hunt recovery: C1-5 wave4 full-cap/level-up retry, quota exhaustion, reserved slot, pooled visibility/bounds, lost targets, dedup and sequential completion across 15 stages passed');

{const s=scene();s.ensureHuntTarget();const e=s.foes[0];e.x=2200;e.y=0;s.player.x=1800;s.tickWaveObjective(.1);assert.equal(e.x,1880);assert(!e._huntFlee);}
