const assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),s=fs.readFileSync('game.js','utf8');
function method(n){const a=s.indexOf('  '+n+'(',s.indexOf('class Game extends')),m=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(s.slice(a+1));assert(a>=0&&m);return s.slice(a,a+1+m.index);}
let now=0,taps=0,destroyed=0;const ctx={performance:{now:()=>now}};vm.createContext(ctx);const C=vm.runInContext('class C{'+['cancelMenuMotion','menuPointerDown','menuPointerMove','menuPointerUp','tickMenuMotion','setMenuScroll'].map(method).join('\n')+'\n} C',ctx);
function scene(){const c=new C();Object.assign(c,{state:'menu',_mScroll:100,_mScrollMax:1500,menu:{y:0},tapZones:[{x:0,y:100,w:100,h:50,fn:()=>{}}],camUI:g=>g,add:{graphics:()=>({setScrollFactor(){return this},setDepth(){return this},fillStyle(){return this},fillRoundedRect(){return this},destroy(){destroyed++}})},handleTap:()=>taps++});return c;}
let c=scene();c.menuPointerDown({id:1,x:20,y:20});assert(c._menuPress);c.menuPointerUp({id:1,x:20,y:20});assert.equal(taps,1);assert(!c._menuPress);
c=scene();now=0;c.menuPointerDown({id:1,x:20,y:200});now=20;c.menuPointerMove({id:1,x:20,y:120});assert.equal(c._mScroll,180);now=30;c.menuPointerUp({id:1,x:20,y:120});assert.equal(taps,1);assert(c._mVelocity>0);const before=c._mScroll;c.tickMenuMotion(1/60);assert(c._mScroll>before);
c.menuPointerDown({id:2,x:20,y:20});c.menuPointerUp({id:2,x:20,y:20});assert.equal(taps,1);assert.equal(c._mVelocity,0);
c=scene();c.menuPointerDown({id:1,x:20,y:20});now+=20;c.menuPointerMove({id:1,x:45,y:20});c.menuPointerUp({id:1,x:45,y:20});assert.equal(taps,1);assert(!c._menuPress);
c=scene();c.menuPointerDown({id:1,x:20,y:200});now+=20;c.menuPointerMove({id:1,x:20,y:120});now+=200;c.menuPointerUp({id:1,x:20,y:120});assert.equal(c._mVelocity,0);
const a=scene(),b=scene();a._mVelocity=b._mVelocity=900;for(let i=0;i<60;i++)a.tickMenuMotion(1/60);for(let i=0;i<120;i++)b.tickMenuMotion(1/120);assert(Math.abs(a._mScroll-b._mScroll)<.5);
c=scene();c._mScroll=1499;c._mVelocity=1000;c.tickMenuMotion(.05);assert.equal(c._mScroll,1500);assert.equal(c._mVelocity,0);c._gearPinned={y:0};c.tapZones=[{fixedY:500,y:500}];c.setMenuScroll(200);assert.equal(c._gearPinned.y,200);assert.equal(c.tapZones[0].y,700);
c.menuPointerDown({id:1,x:20,y:20});c._mVelocity=100;c.state='play';c.tickMenuMotion(.016);assert(!c._mDrag);assert.equal(c._mVelocity,0);assert(s.includes('this.cancelMenuMotion(); const s=this.menuScreen'));assert(s.includes("this.input.on('pointerupoutside'"));console.log('Menu touch: immediate press, drag suppression, stop tap, stale velocity, frame-rate independent decay, bounds, fixed footer and lifecycle passed');
