const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {scene:baseScene,enemy,object,shot}=require('./mint-impaler.test.cjs');
const source=fs.readFileSync('game.js','utf8');
function method(n){const at=source.indexOf('  '+n+'(');assert(at>=0,n);const tail=source.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);return source.slice(at,at+1+next.index);}
const ctx={Math,COLORS:{ice:1},BALANCE:{skillPower:{frost:1}},FLAVOR_INFUSIONS:[],Sfx:{frost(){}},Phaser:{Math:{FloatBetween:()=>0}}};vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('const BASIC_EVO_DESC='),source.indexOf('/* ---- BASIC ATTACK PROTOTYPE'))+source.slice(source.indexOf('const BASIC_ATTACKS = {'),source.indexOf('// 🛤 Build Path'))+source.slice(source.indexOf('function mintVolleyProfile('),source.indexOf('function pickMintCards(')),ctx);
const names=['basicAttackInfo','mintBullet','mintBurstFx','mintHeavyImpact','queueHailstorm','castFrostLance','impalerTarget','castImpalerLance','tickImpalerCharge','releaseImpalerCharge','impaleStacks','applyImpale','hitImpaler','_hitEnemyCore','killBullet','artDelay','trackArtVfx','clearArtVfx','glacierBrittle','glacierPrimed','glacierHitPower','glacierFrostHit','glacierEcho','mintChill','glacierShatter','frostShatterBurst'];
const Scene=vm.runInContext('class Scene{'+names.map(method).join('\n')+'\n}Scene',ctx);
function scene(path='barrage',foes=[]){for(const e of foes)e.setVelocity=function(x,y){this.body.velocity.x=x;this.body.velocity.y=y;};const s=baseScene(foes);Object.setPrototypeOf(s,Scene.prototype);delete s.mintBullet;delete s.mintChill;s.tweens.add=()=>{};Object.assign(s,{character:'mint',skills:{frost:1},player:{active:true,x:0,y:0,dmgMul:1,_pt:{}},hitCratesInRadius(){},ptOnFreeze(){},burst(){},screenShake(){},hitStop(){}});s.basicAttack.path=path;s.basicAttack.evolved=true;s.basicAttack._pm={count:0,range:0,dmg:1};s.bullets={children:{iterate(fn){s.shots.forEach(fn);}}};return s;}
// Path-derived identity needs no new save key. All old Recipe evolved flags work.
for(const [path,name] of [['barrage','Hailstorm Arsenal'],['glacier','Absolute Zero'],['pierce','Heaven Piercer']]){const s=scene(path);assert.equal(s.basicAttackInfo().evolution,name);assert(s.basicAttackInfo().evolutionDesc.length>40);}
{const s=scene();s.character='momo';assert.equal(s.basicAttackInfo().evolution,'Heartstorm Blaster');}
// Arsenal queues exactly six, at 90ms intervals, retargeting live priority; never stacks cooldowns.
{const e=enemy(),s=scene('barrage',[e]);s.queueHailstorm(1,20,.6,s.basicAttack);s.queueHailstorm(1,20,.6,s.basicAttack);assert.equal(s.queue.length,6);assert.deepEqual(s.queue.map(q=>q.at),[0,90,180,270,360,450]);for(let k=0;k<6;k++)s.advance(k?90:0);assert.equal(s.shots.length,6);assert(s.shots.every(b=>b.dmg===14&&!b.shatterInfo));s.queueHailstorm(1,20,.6,s.basicAttack);assert.equal(s.queue.length,0);s.time.now=4000;s.queueHailstorm(1,20,.6,s.basicAttack);assert.equal(s.queue.length,6);}
for(const cancel of ['clear','menu','replace']){const s=scene('barrage',[enemy()]);s.queueHailstorm(1,20,.6,s.basicAttack);if(cancel==='clear')s.clearArtVfx();else if(cancel==='menu')s.state='menu';else s.basicAttack={path:'barrage',evolved:true};s.advance(1000);assert.equal(s.shots.length,0);}
// Heaven Piercer: successful full spawns only; partial/capped attempts never advance cycle.
{const s=scene('pierce',[enemy()]),one=shot(s),partial=shot(s,false),two=shot(s),three=shot(s);assert(!one.impaler.giant&&!partial.impaler.giant&&!two.impaler.giant);assert(three.impaler.giant);assert.equal(s.basicAttack._impalerFullShots,3);assert(Math.abs(three.dmg/two.dmg-1.35)<1e-9);assert.equal(three.impaler.pierces,8);assert.equal(three.artHeight,80);assert.equal(one.scale,three.scale);s.clearArtVfx();assert.equal(s.basicAttack._impalerFullShots,0);}
{const e=enemy({isBoss:true,_mintImpale:3,_mintImpaleAt:0}),s=scene('pierce',[e]);s.basicAttack.lv.p_shatterpt=2;s.basicAttack.lv.linger=2;s.basicAttack._impalerFullShots=2;const b=shot(s);s.hitImpaler(b,e);assert.equal(e._mintImpale,0);const impact=s.hits[0].n;assert(Math.abs(s.hits[1].n-impact*1.8*1.36*1.35)<1e-8);assert.equal(b.active,false);}
{const e=enemy({isMini:true,_phaseInvuln:1,_mintImpale:3,_mintImpaleAt:0}),s=scene('pierce',[e]);s.basicAttack._impalerFullShots=2;s.hitImpaler(shot(s),e);assert.equal(s.hits.length,0);assert.equal(e._mintImpale,3);}
// Absolute Zero widens ONLY opening reaction and grants exactly one extra chain step.
{const foes=[0,170,270,370,470].map(x=>enemy({x,frozen:5,_glacierFrost:2,_glacierFrostAt:0})),s=scene('glacier',foes);s.basicAttack.lv.p_chainshatter=2;foes[0]._glacierFrost=3;s.glacierShatter(foes[0]);assert.equal(s._glacierBursts,4);assert.equal(foes[4]._glacierFrost,3);assert.equal(s._glacierBusy,false);}
{const e=enemy({isBoss:true,_glacierBrittleUntil:3000,_glacierFrost:3}),s=scene('glacier',[e]);s.glacierShatter(e);assert.equal(s.hits[0].n,36);assert.equal(e.frozen,0);}
// Existing ranks preserve power/count conversion; Glacier bloom avoids a shard shower.
{const foes=[enemy(),enemy({x:20})],a=scene('glacier',foes),b=scene('glacier',foes);a.frostShatterBurst(0,0,0,3,10,.6,1.2,false,1);b.frostShatterBurst(0,0,0,6,10,.6,1.2,false,1);assert.equal(a.shots.length,0);assert.equal(b.shots.length,0);assert(Math.abs(b.hits[0].n/a.hits[0].n-1.24)<1e-9);}
{const s=scene('barrage',[enemy()]);s.basicAttack.lv.linger=3;s.basicAttack._pm.count=4;s.castFrostLance(5,false,1,s.basicAttack);assert.equal(s.shots.length,3);assert.equal(s.shots[0].shatterInfo.dmg,36*.55*1.72);assert.equal(s.queue.filter(q=>q.at<=450).length,6);}
{const s=scene('glacier');s.basicAttack.lv.linger=1;s.basicAttack._pm.count=4;s.castFrostLance(5,false,1,s.basicAttack);assert.equal(s.shots.length,4);assert.equal(s.shots[0].shatterInfo.count,4);assert(Math.abs(s.shots[0].shatterInfo.dmg-36*.55*1.24)<1e-9);}
{const s=scene('pierce');s.basicAttack.evolved=false;shot(s);shot(s);assert.equal(s.basicAttack._impalerFullShots||0,0);s.basicAttack.evolved=true;assert(!shot(s).impaler.giant);}
{const s=scene('glacier',[enemy()]);s.frostShatterBurst(0,0,0,8,10,.6,1.2,false,1);assert.equal(s.hits[0].n,10*1.4*1.6);assert.equal(s.shots.length,0);}
// Dense crowd stress: 100 repeated blooms cannot bypass shared projectile/shard/VFX budgets.
{const foes=Array.from({length:500},(_,x)=>enemy({x:x%20})),s=scene('barrage',foes);let fx=0;s.spawnFxAnim=()=>{fx++;return object();};for(let k=0;k<100;k++)s.frostShatterBurst(0,0,0,8,10,.6,1.2,false,1);assert.equal(s.shots.length,12);assert.equal(fx,3);assert.equal(s.hits.length,2400);assert(s.shots.every(b=>b.dmg===12.4));s.time.now=200;for(let k=0;k<10;k++)s.frostShatterBurst(0,0,0,8,10,.6,1.2,false,1);assert.equal(s.shots.length,24);assert.equal(fx,6);assert.equal(s.mintBullet(0,0,1,1),null);}
{const s=scene('pierce');for(let k=0;k<24;k++)s.mintBullet(0,0,1,1);shot(s);assert.equal(s.basicAttack._impalerFullShots||0,0);assert.equal(s.shots.length,24);}
// Stale normal lances/shards cannot affect the next run, and saturated casts make no phantom blooms.
{const e=enemy(),s=scene('barrage',[e]),b=s.mintBullet(0,0,1,1);b.iceNeedle={};s.clearArtVfx();s._hitEnemyCore(b,e);assert.equal(s.hits.length,0);assert.equal(b.active,false);}
{const s=scene('glacier');for(let k=0;k<24;k++)s.mintBullet(0,0,1,1);s.castFrostLance(5,false,1,s.basicAttack);assert.equal(s.queue.length,0);}
// Impact pauses/shake are rate-limited, and visual throttling does not suppress damage.
{const s=scene('pierce');let stop=0;s.hitStop=ms=>{assert.equal(ms,25);stop++;};for(let k=0;k<20;k++)s.mintHeavyImpact();assert.equal(stop,1);s.time.now=350;s.mintHeavyImpact();assert.equal(stop,2);}
console.log('Mint M4: path Evolutions, Arsenal scheduling/cancellation, Heaven cycle/Rupture, Absolute Zero chain, saved investment, dense-crowd budgets and stale-shot guards passed');
