const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('game.js','utf8');
function method(n){const at=source.indexOf('  '+n+'('),tail=source.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);assert(at>=0&&next,n);return source.slice(at,at+1+next.index);}
const Scene=vm.runInNewContext('class Scene{'+['stopEnemyPresentation','resetEnemyPresentation','enemyAction','tickEnemyPresentation','stage5EnemyPose','playEnemyDeath'].map(method).join('\n')+'\n}Scene',{Math});
const known=new Set(['c3_e_basic_walk','e_acid_walk','e_crown_ripper_walk','future_walk','future_attack','future_death']);
const s=new Scene();s.anims={exists:k=>known.has(k)};s.player={y:0};
function mob(key,frame=0){return {active:true,texture:{key},frame:{name:frame},baseScale:0.7,x:20,y:30,body:{velocity:{x:0,y:0}},plays:[],anims:{isPlaying:false,isPaused:false,timeScale:1,stop(){this.isPlaying=false;this.isPaused=false;},pause(){this.isPaused=true;},resume(){this.isPaused=false;}},setTexture(k,f){this.texture={key:k};this.frame={name:f};return this;},setVelocity(x,y){this.body.velocity={x,y};return this;},setScale(x,y=x){this.scaleX=x;this.scaleY=y;return this;},play(k){this.plays.push(k);this.anims.isPlaying=true;this.anims.isPaused=false;return this;}};}
// Real walk animation is driven by movement; idle doesn't keep running in place.
{const e=mob('c3_e_basic');s.resetEnemyPresentation(e);assert.equal(e._enemyAnimState,'idle');e.setVelocity(70,0);s.tickEnemyPresentation(e,0.016);assert.equal(e.plays.at(-1),'c3_e_basic_walk');assert.equal(e.anims.timeScale,1);for(let i=0;i<60;i++)s.tickEnemyPresentation(e,0.016);assert.equal(e.plays.length,1,'Do not restart loop every tick');s.enemyAction(e,'hurt',120);assert.equal(e._enemyAction,null,'Missing hurt art must not stop a walk cycle');assert.equal(e.rotation,0);assert.equal(e.scaleX,e.scaleY);e.setVelocity(140,0);s.tickEnemyPresentation(e,0.016);assert.equal(e.anims.timeScale,1.5);e.setVelocity(0,0);s.tickEnemyPresentation(e,0.016);assert.equal(e._enemyAnimState,'idle');assert(!e.anims.isPlaying);}
// Freeze pauses an existing loop and preserves an authored action until thaw.
{const e=mob('e_acid');s.resetEnemyPresentation(e);e.setVelocity(55,0);s.tickEnemyPresentation(e,0.016);e.frozen=1;s.tickEnemyPresentation(e,0.4);assert(e.anims.isPaused);e.frozen=0;s.tickEnemyPresentation(e,0.016);assert(!e.anims.isPaused);s.enemyAction(e,'attack',260,3);e.frozen=1;s.tickEnemyPresentation(e,2);assert.equal(e._enemyActionT,0.26);assert.equal(e.frame.name,3);e.frozen=0;s.tickEnemyPresentation(e,0.25);assert.equal(e.frame.name,3);s.tickEnemyPresentation(e,0.02);assert.equal(e.plays.at(-1),'e_acid_walk');assert.equal(e._enemyAction,null);}
// Rapid damage must not replace telegraph/attack; latest action wins without stale timers.
{const e=mob('e_crown_ripper');s.resetEnemyPresentation(e);e.setVelocity(70,0);s.stage5EnemyPose(e,4,400);s.enemyAction(e,'hurt',120);assert.equal(e.frame.name,4);s.stage5EnemyPose(e,5,340);s.tickEnemyPresentation(e,0.30);assert.equal(e.frame.name,5);s.tickEnemyPresentation(e,0.05);assert.equal(e._enemyAnimState,'walk');assert.equal(e.plays.at(-1),'e_crown_ripper_walk');}
// Recycle the same object from a frozen attacker to an atlas monster. Preserve its species frame.
{const e=mob('e_acid');s.resetEnemyPresentation(e);s.enemyAction(e,'attack',260,3);e.frozen=1;s.tickEnemyPresentation(e,0.1);s.stopEnemyPresentation(e);e.frozen=0;e.setTexture('ch2_enemy_atlas',5);s.resetEnemyPresentation(e,5);e.setVelocity(35,0);s.tickEnemyPresentation(e,1);assert.equal(e.texture.key,'ch2_enemy_atlas');assert.equal(e.frame.name,5);assert.equal(e._enemyAction,null);assert.equal(e._enemyFrozen,false);assert.equal(e.anims.timeScale,0.65);assert.equal(e._sqX,1);assert.equal(e._sqY,1);assert.equal(e.scaleX,e.scaleY);}
// Future art needs no new AI code: optional action clips are selected by the same controller.
{const e=mob('future');s.resetEnemyPresentation(e);s.enemyAction(e,'attack',300);assert.equal(e.plays.at(-1),'future_attack');s.tickEnemyPresentation(e,0.31);assert.equal(e._enemyAnimState,'idle');}
// Boss/miniboss presentation remains controlled by its existing phase/pose system.
{const e=mob('boss1');e.isBoss=true;s.tickEnemyPresentation(e,1);s.enemyAction(e,'hurt',120);assert.equal(e._enemyAction,undefined);assert.equal(e.plays.length,0);}
// Authored death plays on a ghost so loot and pool reuse are immediate and independent.
{const e=mob('future'),g={once(k,f){this.done=f;return this;},setScale(){return this;},setFlipX(){return this;},setDepth(){return this;},play(k){this.key=k;},destroy(){this.destroyed=true;}};Object.assign(s,{fxOk:()=>true,camWorld:o=>o,trackArtVfx:o=>o,add:{sprite:()=>g},deathFling(){throw Error('Must use available death clip');}});s.playEnemyDeath(e);assert.equal(g.key,'future_death');assert(e.active);g.done();assert(g.destroyed);}
const at=source.indexOf('function registerEnemyActionAnimations('),end=source.indexOf('const ASSET_SHEETS =',at),defs={future:{actions:{idle:{frames:[0,1],rate:4},attack:{start:8,frames:4,rate:12},death:{texture:'future_death_sheet',frames:6}}}};
const register=vm.runInNewContext(source.slice(at,end)+'\nregisterEnemyActionAnimations',{ASSET_SHEETS:defs,Math});const clips=new Map(),scene={textures:{exists:()=>true},anims:{exists:k=>clips.has(k),generateFrameNumbers:(key,{start,end})=>Array.from({length:end-start+1},(_,i)=>({key,frame:start+i})),create(c){clips.set(c.key,c);}}};register(scene);register(scene);assert.equal(clips.size,3);assert.equal(clips.get('future_idle').repeat,-1);assert.equal(clips.get('future_attack').repeat,0);assert.equal(clips.get('future_attack').frames[0].frame,8);assert.equal(clips.get('future_death').frames[0].key,'future_death_sheet');
assert(source.includes('this.tickEnemyPresentation(e,dt);\n      if(e.frozen>0)'));
assert(!method('stage5EnemyPose').includes('delayedCall'));
assert(method('spawnEnemy').includes('this.resetEnemyPresentation(e,atlasFrame)'));
assert(method('spawnElite').includes('this.resetEnemyPresentation(e,eliteFrame)'));
assert(method('clearEnemies').includes('this.stopEnemyPresentation(e)'));
console.log('Monster controller: movement/idle, stable scale, freeze/thaw, action priority, pooled species frame, death ghost and deferred action registration passed');
