const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('game.js','utf8');
function fn(name){const start=source.indexOf('function '+name+'('),next=source.indexOf('\n}',start);return source.slice(start,next+2);}
function method(n){const at=source.indexOf('  '+n+'('),tail=source.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);return source.slice(at,at+1+next.index);}
// Load real affix definitions and functions, independent of Phaser startup.
const ctx={STAT_CAPS:{cdMulMin:.25},GEAR_ALL:[{id:'test_weapon',tier:'common',slot:'weapon'},{id:'test_armor',tier:'rare',slot:'armor'},{id:'starter',tier:'start',slot:'weapon'}]};vm.createContext(ctx);
vm.runInContext(source.slice(source.indexOf('const AFFIX_POOL ='),source.indexOf('/* ---- CURRENCY (Phase 2)')),ctx);
vm.runInContext(source.slice(source.indexOf('function gearBaseStats('),source.indexOf('function gearPool(')),ctx);
vm.runInContext('this.defs=allAffixDefs();this.helpers={gearBaseStats,applyGearBaseStats,gearAttackRoll,armorDamageMultiplier,affixBestTierForItem,rollOneAffix,rollOneAffixLocked,tierChances,affixTierForValue};',ctx);
const h=ctx.helpers,vamp=ctx.defs.find(d=>d.id==='vampiric');assert.equal(vamp.tiers.length,3);
for(const mod of ctx.defs){if(mod.tiers.length<11)assert.equal(new Set(mod.tiers.map(b=>b.join(':'))).size,mod.tiers.length,mod.id);for(const level of [1,12,30,60,100]){const item={baseId:'test_weapon',itemLevel:level,grade:'common'},best=h.affixBestTierForItem(item,mod),ch=h.tierChances(best,mod.tiers.length-1);assert(best<mod.tiers.length);assert(Math.abs(Object.values(ch).reduce((a,b)=>a+b,0)-1)<1e-9);for(let i=0;i<15;i++){const a=h.rollOneAffix(mod,best,level),b=mod.tiers[a.t];assert(a.t>=best&&a.t<mod.tiers.length);assert(a.v>=b[0]&&a.v<=b[1]);const locked=h.rollOneAffixLocked(mod,best,level,{id:mod.id,t:best});assert.equal(locked.t,best);}}}
const w={baseId:'test_weapon',slot:'weapon',itemLevel:10},a={baseId:'test_armor',slot:'armor',itemLevel:10};assert(h.gearBaseStats(w).attackMax>0);assert(h.gearBaseStats(a).armor>0);assert(h.gearBaseStats({...w,itemLevel:100}).attackMin>h.gearBaseStats(w).attackMin);assert(h.gearBaseStats({...a,enhanceLv:10}).armor>=h.gearBaseStats(a).armor);
const p={};h.applyGearBaseStats(p,w);h.applyGearBaseStats(p,a);assert.equal(h.gearAttackRoll(p,()=>0),p.gearAttackMin);assert.equal(h.gearAttackRoll(p,()=>.99999),p.gearAttackMax);assert(h.armorDamageMultiplier(p)<1);assert.equal(h.armorDamageMultiplier({armor:0}),1);
assert.equal(h.gearBaseStats({baseId:'starter',slot:'weapon',itemLevel:1}).attackMax,0);
// Saved affix value survives re-labelling, including inbox entries.
const Migration=vm.runInContext('class Migration{'+method('migrateAffixTiers11').trim().replace(/,$/,'')+'}Migration',ctx),m=new Migration();m.data={gearItems:[{affixes:[{id:'vampiric',v:13,t:8,t11:1}]}],gearInbox:[{affixes:[{id:'edge',v:2,t:10,t11:1}]}]};m.migrateAffixTiers11();assert.equal(m.data.gearItems[0].affixes[0].v,13);assert.equal(m.data.gearItems[0].affixes[0].t,1);assert.equal(m.data.gearItems[0].affixes[0].tierSchema,2);m.migrateAffixTiers11();assert.equal(m.data.gearItems[0].affixes[0].v,13);
// Render entry choices and store tiles using a scene double; every hit area must fit.
const Save={data:{sugar:2000,shards:5,bazaarBought:[]},bazaarRefreshCost:()=>20,sugarOrder:()=>null,currency:()=>3};
const C=vm.runInNewContext('class Scene{'+['openDifficultyChoice','startStoryStage','paintedNavButton','bazaarProductCard','buildBazaar','drawHeroesTabs'].map(method).join('\n')+'}Scene',{Save,STAGES:[{name:'Stage 1'}],DIFFS:[{name:'Normal',reward:1},{name:'Hard',reward:1.5},{name:'Hell',reward:2}],COLORS:{grape:1,pink:2,mint:3},GEAR_BUY:{common:160},CURRENCY_BUY:{alt:60},TIER_LABEL:{common:{name:'Common'}},SUGAR_ORDERS:[{id:'threads',unit:'thread',base:12,cost:120,name:'Thread Hunt'}],CURRENCY:[{key:'alt',asset:'currency_alt',name:'Twist Cream'}],currencyDef:()=>({asset:'currency_alt',name:'Material'}),Sfx:{}});
function scene(W,H){const s=new C();s.W=W;s.H=H;s.zones=[];s.products=[];const node=new Proxy({scene:true},{get(o,k){if(k in o)return o[k];return()=>node;}});s.add={graphics:()=>node,text:()=>node,image:()=>node};s.menu={removeAll(){},add(){},setVisible(){}};s.textures={exists:()=>true,get:()=>({has:()=>true})};s._hdrShift=()=>W<=H?30:0;s._screenBg=()=>{};s._zone=(x,y,w,h,fn)=>{assert(x>=0&&y>=0&&x+w<=W+.01&&y+h<=H+.01,JSON.stringify({W,H,x,y,w,h}));s.zones.push({x,y,w,h,fn});};s.uiPillBtn=(c,x,y,w,h,col,ic,txt,fn)=>s._zone(x-w/2,y-h/2,w,h,fn);s._rowBtn=(y,h,art,name,desc,label,col,fn)=>s._zone(14,y,W-28,h,fn);s.bazaarStock=()=>({zone:1,chapter:1,gear:[1,2,3].map(i=>({id:'g'+i,name:'Equipment '+i,tier:'common'})),cur:[1,2,3].map(i=>({key:'alt',qty:i}))});s.startRun=()=>{};return s;}
for(const [W,H] of [[320,568],[390,844],[768,390]]){for(const tab of ['buy','gamble','orders','sell']){const s=scene(W,H);s._bazTab=tab;s.buildBazaar();if(tab==='buy'){const refresh=s.zones[4];for(const nav of s.zones.slice(0,4)){const overlap=nav.x<refresh.x+refresh.w&&nav.x+nav.w>refresh.x&&nav.y<refresh.y+refresh.h&&nav.y+nav.h>refresh.y;assert(!overlap,'Refresh overlaps navigation');}}}const s=scene(W,H);s._challengeRequested=['iron'];s.openDifficultyChoice(0);assert.equal(s._challengeRequested,null);assert.equal(s.zones.length,0);assert.equal(s.stageDiff,1);}
assert(!method('openDifficultyChoice').includes('uiPillBtn'));assert(!method('openLevelUp').includes('drawLevelActionBar'));assert(!source.includes('  drawLevelActionBar('));assert(!method('pickCardAt').includes('banishCard'));assert(method('startRun').includes('const challenge=null'));assert(method('damage').includes('gearAttackRoll(this.player)'));assert(method('hurtPlayer').includes('armorDamageMultiplier(this.player)'));assert(method('renderReplayProgress').includes('replayProgressFrame.setVisible(true)'));assert(method('buildHeroes').includes('this.buildTalents()'));assert(method('buildHeroes').includes('this.buildStats()'));
console.log('Progression polish: compact tier probabilities/locks, save value preservation, real gear stats, story curse isolation, store hit areas and Refresh separation at three sizes, direct entry, Heroes routes and replay art passed');

vm.runInContext(source.slice(source.indexOf('const GEAR_COMPARE_STATS ='),source.indexOf('/* ---- Save:')),ctx);
const compact=vm.runInContext("gearCompareRows(null,{baseId:'test_weapon',slot:'weapon',itemLevel:10}).filter(r=>r.range)",ctx);assert.equal(compact.length,1);assert.equal(compact[0].label,'ATK');ctx.compact=compact[0];assert.match(vm.runInContext('gearStatText(compact,compact.to)',ctx),/^\d+-\d+$/);
