const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const s=fs.readFileSync('game.js','utf8'),block=(a,b)=>s.slice(s.indexOf(a),s.indexOf(b));
const baseline=JSON.parse(fs.readFileSync('tests/fixtures/talent-art-baseline.json'));
assert.equal(crypto.createHash('sha256').update(block('const CHAR_TALENTS = {','// v4.88: Passive')).digest('hex'),baseline.definitionSha256,'effects/costs/prerequisites unchanged from 6.55.99');
function method(name){const at=s.indexOf('  '+name+'('),tail=s.slice(at+1),next=/\n  [A-Za-z_]\w*\([^\n]*\)\s*\{/.exec(tail);assert(at>=0&&next);return s.slice(at,at+1+next.index);}
const heroes=['momo','mint','cocoa','taro','yuzu','sesame','berry'],cp={lvl:10,exp:0,tp:40,tal:{}},ctx={CHARACTERS:Object.fromEntries(heroes.map(h=>[h,{name:h}])),CHAR_ORDER:heroes,FIGHTER_PLAYTEST_ALL:true,Save:{data:{character:'momo',chars:heroes,sugar:1000},cp:()=>cp,save(){}},Sfx:{select(){},progress(){}},charExpNeed:()=>100};vm.createContext(ctx);
vm.runInContext(block('const BASIC_PATHS={','// 🍯 Flavor Infusion')+block('const TALENT_ICON_FRAMES =','// EXP ที่ต้องใช้'),ctx);
const a=vm.runInContext('({TALENT_ICON_FRAMES,CHAR_TALENTS,BASIC_PATHS,talentBranch})',ctx);
const Scene=vm.runInContext('class Scene{'+method('talentIcon')+method('buildTalents')+'\n}Scene',ctx);
const report=JSON.parse(fs.readFileSync('assets/incoming/talent_icons/PACKING.json'));let total=0;
for(const hero of heroes){const nodes=a.CHAR_TALENTS[hero].concat((a.BASIC_PATHS[hero]||[]).flatMap(p=>a.talentBranch(p)));assert.equal(Object.keys(a.TALENT_ICON_FRAMES[hero]).length,nodes.length);assert.equal(report[hero].nodes.length,nodes.length);const hashes=new Set();for(let i=0;i<nodes.length;i++){assert.equal(a.TALENT_ICON_FRAMES[hero][nodes[i].id],i);assert.equal(report[hero].nodes[i].id,nodes[i].id);const b=report[hero].nodes[i].packedBounds;assert(b[0]>=7&&b[1]>=7&&b[2]<=121&&b[3]<=121);}const png=fs.readFileSync('assets/incoming/talent_icons/'+hero+'_talents.png');assert.equal(png.readUInt32BE(16),768);assert.equal(png.readUInt32BE(20),896);assert.equal(png[25],6);const webp=fs.readFileSync('assets/art/talents/'+hero+'_talents.webp');assert.equal(webp.toString('ascii',0,4),'RIFF');assert.equal(webp.toString('ascii',12,16),'VP8L');assert(webp.readUInt32LE(21)&0x10000000);total+=nodes.length;}
assert.equal(total,218);
for(const [W,H] of [[390,844],[320,640],[844,390]])for(const hero of heroes)for(const tab of ['core',...(a.BASIC_PATHS[hero]||[]).map(p=>p.id)])for(const available of [true,false]){
 ctx.Save.data.character=hero;cp.tal={};const items=[],images=[],zones=[];let serial=0;
 function item(kind,x=0,y=0,text=''){const o={kind,x,y,text,width:String(text).length*7,active:true,serial:serial++,alpha:1,setOrigin(){return this},setAlpha(v){this.alpha=v;return this},setDisplaySize(w,h){this.displayWidth=w;this.displayHeight=h;return this}};const proxy=new Proxy(o,{get(t,k){return k in t?t[k]:(...args)=>proxy;}});return proxy;}
 const scene=new Scene();Object.assign(scene,{W,H,_talTab:tab,menu:{removeAll(){items.length=0},add(v){items.push(...(Array.isArray(v)?v:[v]))},setVisible(){}},add:{graphics:()=>item('graphics'),text:(x,y,t)=>item('text',x,y,t),image:(x,y,key,frame)=>{const o=item('image',x,y);Object.assign(o,{key,frame});images.push(o);return o;}},textures:{exists:()=>available},_screenBg(){},drawHeroesTabs(){},_darken:c=>c,_zone:(x,y,w,h,fn)=>zones.push({x,y,w,h,fn}),uiPillBtn(){},menuToast(){},buildMenuScreen(){}});
 scene.buildTalents();const nodes=tab==='core'?a.CHAR_TALENTS[hero]:a.talentBranch(a.BASIC_PATHS[hero].find(p=>p.id===tab));assert.equal(images.length,available?nodes.length+1:0);assert.equal(zones.length, (a.BASIC_PATHS[hero]||[]).length+1+nodes.length+3);assert(items.some(o=>o.text==='🔒'));if(available){assert.equal(images[0].alpha,1);assert(images.slice(1,-1).some(o=>o.alpha===.35));for(const icon of images){assert(icon.x>0&&icon.x<W);assert(icon.displayWidth<=47);const index=items.indexOf(icon);assert(index>0&&items[index-1].kind==='graphics','art must be above its panel');}assert.equal(images.at(-1).frame,images[0].frame);}else assert(items.some(o=>o.text===nodes[0].emoji),'missing texture preserves emoji');
 zones.at(-1).fn();assert.equal(cp.tal[nodes[0].id],1);assert.equal(cp.tp,39);cp.tp=40;
 if(available)for(const node of nodes){images.length=0;zones.length=0;scene._talSel=node.id;scene.buildTalents();assert.equal(images.at(-1).frame,a.TALENT_ICON_FRAMES[hero][node.id],'every selection shares the node icon');}
}
const menuRe=vm.runInContext(block('const MENU_GROUPS=','const ENDGAME_ART_RE=' )+'\nmenuGroupRe',ctx);for(const page of ['char','chars','talents'])for(const hero of heroes)assert(menuRe(page).test('assets/art/talents/'+hero+'_talents.webp'));
console.log('Talent art: all 218 mappings, alpha atlas contracts, unchanged definitions, actual tree/detail/lock/fallback/layer order at three viewports and original point spending passed');
